### ISSUE TITLE
Allow setting font for native controls (widgets)

### ISSUE THREAD

**Issue by ccoupe** [shoes/shoes3#179]
It's possible to set the font for any NSControl or Gtk3 widget but they do it differently. Gtk wants a pango font description (or it creates one from a string).  OSX wants a fontObject (created from NSFont)

Shoes already has rich set of style names for textblock  and a list of all the fonts available. We just need some native code similar shoes_app_style_for () to  map the styles to to gtk_widgets or NSFont objects instead of cairo drawing attributes. And update all controls to do it.

**Comment by ccoupe** [comment]
I created a widgetfont branch. I start with button  Here the test script (bugs/bug179.rb)
```ruby
Shoes.app width: 300, height: 200 do
  stack do
    button "Button", font: "mono bold 14",fill: yellow, stroke: red do
    end
    button "Normal" do
    end
  end
end
```
![btnfont](https://user-images.githubusercontent.com/222691/30677929-f9c04d3e-9e4b-11e7-91fe-923aa64186bd.png)

Yes, the background is not yellow and and the stoke is not red -- but the font did change. And its only for linux/windows ... Work in progress.

**Comment by ccoupe** [comment]
![colorbtn](https://user-images.githubusercontent.com/222691/30724474-381ca2b2-9efb-11e7-9c74-e2ad59f072ad.png)

The background color , #353 appears to be a incompatible idea. It's deprecated in Gtk 3.16 and works oddly below that when it deprecates an even older call. Also, it's not directly supported by Cocoa. However, both toolkits support images in a button along with some positioning options for image vs text - that seems doable.  

There are issues with all those pango attributes& list  that need dereferencing so it's still incomplete.

**Comment by ccoupe** [comment]
Here's tooltip for an icon button. 
![iconbutton](https://user-images.githubusercontent.com/222691/30727634-a565c6dc-9f0f-11e7-94b7-4aa226cd9c65.png)

Script:
```Ruby
Shoes.app width: 300, height: 200 do
  stack do
    flow do
      button "Button", font: "mono bold 14",width: 200, stroke: red,
          tooltip: "Red mono" do
      end
      button "icon", width: 30, height: 30, image: "#{DIR}/static/icon-info.png",
          tooltip: "info button" do
      end
    end
    button "Normal", tooltip: "Normal" do
    end
  end
end
```
No, it's not correct, IMO but I like the direction.  It's not like people haven't asked for this.

**Comment by BackOrder** [comment]
It's looking good and promising.

**Comment by ccoupe** [comment]
Switching to OSX.  
![osxbtn](https://user-images.githubusercontent.com/222691/30769365-fa5667f4-9fd3-11e7-9864-8e154da5b136.png)

While it might look OK relative to Gtk it's incomplete (both are). That font: string in the bug179.rb is
platform specific. 'mono bold 14' doesn't exist in the OSX/NSFont world by that name. I'm OK with using platform specific font names. If a Shoes developer really want this level of control of button appearance then they also have to do things for their platform of choice. Different font names applies to Windows too.

**Comment by BackOrder** [comment]
Besides, a Shoes developer may want to include their own fonts with their app. Shoes is provided with two fonts already. Otherwise they may choose depending on the platform; this is what is done on web pages. Seems acceptable.

**Comment by ccoupe** [comment]
This is much better for OSX.  If only gtk3 would behave.
![osxgoodbtn](https://user-images.githubusercontent.com/222691/30778534-93775be8-a095-11e7-9a8e-66e31ac49dc4.png)
Oddly (?)  there is no toolltip support - no code. Now would be good time to fix that while I'm in obj->C mode.

**Comment by ccoupe** [comment]
This just turned a bit  ugly.  The cocoa code was not written to make the visual buttons taller (or shorter) although it does layout with the proper size in Shoes space (osx space - maybe not) - Looks good but isn't good. It _appears_ that the ShoesButton in cocoa does not _properly_ subclass NSControl - we may need  an initWithFrame: selector (aka method) to match cocoa's protocols.  It's worth digging into but it's not going to be a speedy exploration.

**Comment by ccoupe** [comment]
I am also taking to time to refactor the cocoa.m file into individual widgets. `@implementation` section followed by the shoes/ruby code to create and call it. Will be much easier to set font, widget by widget.

**Comment by ccoupe** [comment]
Latest screen shots 
![gtkbestbuttons](https://user-images.githubusercontent.com/222691/31474093-e6442ca6-aeb5-11e7-91fa-f97b9b7fea90.png)
![osxbestbuttons](https://user-images.githubusercontent.com/222691/31474106-eec8f0a0-aeb5-11e7-84c1-393a0f074589.png)

**Comment by BackOrder** [comment]
Looks like great work here. Shouldn't the buttons resize up when the content is too big?

**Comment by ccoupe** [comment]
>  Shouldn't the buttons resize up when the content is too big?

Many issues there :-) On Gtk you can set the height of the button (and it works).  To do that on OSX requires a subclass  of NSButtonCell (deprecated in 10.11) . I did find an interesting replacement at the SYFlatButton project but it won't compile for me. I left an issue there but haven't heard anything. Very obscure Objective-C. Newer Gtk3 (like freebsd ) does pack things a little differently so that's another issue - along with writing a gtkboxalt subclass to calm the chatter of warnings - there are warnings that gtk_box_new is headed for deprecation use gtk_grid instead -so we'd need a  gtkaltgrid.
All worth doing, someday (along with  background color ability or even scaling images to fit.)

Shoes widgets don't change size based on content - they scale it down or clip it to fit the fixed size given at creation. To do otherwise would require another shoes_place_decide/layout engine - way outside the scope of this issue. 

I'm going to move on to listbox since font setting on that seems to have been lost (and it needs moving out of gtk.c) and then setting fonts on other widgets w/o the icon/image problems.

**Comment by ccoupe** [comment]
gtk_grid fun. I'm not doing it correctly yet. 
![gtkgridbuttons](https://user-images.githubusercontent.com/222691/31479559-3db63794-aed5-11e7-95e7-7fa56d4eeccc.png)

**Comment by ccoupe** [comment]
I got gtk grid layout working _well enough_ for buttons with text and images. freebsd screenshoot:
![bsdbestbuttons](https://user-images.githubusercontent.com/222691/31527241-13417c62-af89-11e7-8216-3d26288e8cda.png)

**Comment by BackOrder** [comment]
This is an excellent addition to Shoes. It feels right with what Shoes is trying to accomplish.

By the way, you can get a better font rendering with LCD filtering (subpixel rendering) on FreeBSD.

**Comment by ccoupe** [comment]
> This is an excellent addition to Shoes. It feels right with what Shoes is trying to accomplish.

I think so too. Other widgets need styling. osx need to match. A big H/T to @passenger94 for figuring out how to calm the gtk3 whining. We have much to do to finish his work with the 'alts'

**Comment by ccoupe** [comment]
Somehow bsd got broken. It crashes  early in the shoes startup (pre splash screen). . Linux still works. Go figure, Sigh.  Looking at the other widgets I see 

- listbox could use stroke (font and stroke for osx) font is current supported on Gtk
- editbox could use font, stroke
- editline  could use font, stroke
- slider could use font, stroke
- switch could use the full monte : icon, font, stroke

**Comment by ccoupe** [comment]
Gtk Combo: aka list_box
![gtkcombo](https://user-images.githubusercontent.com/222691/31580694-a26422aa-b114-11e7-902a-bd4ce2f1fc73.png)
Gtk edit_line
![gtkeditline](https://user-images.githubusercontent.com/222691/31580698-d648b87e-b114-11e7-943b-c5297b74400f.png)

**Comment by ccoupe** [comment]
Another road block. edit_box and others uses deprecated calls (gtk 3.16+) so I thought I'd look into the future proof css way.  edit_box is a GtkTextView. Gnome doc/example says to [do this](https://github.com/Shoes3/shoes3/blob/widgetfont/shoes/native/gtk/gtkeditbox.c#L21) but that doesn't work and I haven't found the net wisdom that helps.  Of course, it could be a bug in my older Gtk3 implementation but a 3 year old Linux is not an ancient platform.

**Comment by BackOrder** [comment]
Interesting that you mention CSS because I always thought Shoes had some kind of CSS in mind but never really fully implemented it.

**Comment by ccoupe** [comment]
I'm sure Shoes was _influenced_ by css and other web technologies.  I'm not sure letting app developers override platform themes is a good idea, _cross platform_ . If you just code for a  set of (say) Windows users then it 's a good feature. If the latter, we need to get the 'future proof' css thing working.

**Comment by BackOrder** [comment]
Here is a bug with text overflowing in a button. Seems to be relevant to this issue, somehow.
 
![image](https://user-images.githubusercontent.com/8844578/33153781-e3a9fb7a-cfb1-11e7-9164-e11c5a5254c6.png)

```ruby
Shoes.app(width: 250, height: 100) do
  button("multiline\nbutton", left: 50, top: 25) do
    alert("does it work?")
  end
end
```

**Comment by ccoupe** [comment]
You're looking at a partial implementation of #179 that made it's way into the master branch. On Gtk based system you can set the height of the button. OSX - no.

**Comment by BackOrder** [comment]
Not urgent or anything. Discovered this while testing something else. I would expect Shoes to automatically adjust the button.

**Comment by ccoupe** [comment]
> I would expect Shoes to automatically adjust the button. 

Shoes has never done that - it would screwup the user specified positioning.

**Comment by BackOrder** [comment]
> Shoes has never done that - it would screwup the user specified positioning.

I am not feeling strongly about this. Though overflowing doesn't make any sense. Positioning in Shoes has its own problems. For example, widgets have the ability to be relative, buttons will be side-by-side if no position is given, but arts (cairo elements) totally cannot do that (even with stack and flow). It might be a feature.

It does make a good counter argument where widgets are expected to push things around anyway. So if somehow uses a CR in a button label, they shouldn't mind the button resize to fit. Just saying.

**Comment by ccoupe** [comment]
We have had the discussion before. We need a different layout manager/paradigm and that's a lot of work. Enough work, it might be easier to start from scratch and not call it Shoes. or Use wx-wdiget with a nicer ruby dsl.

**Comment by BackOrder** [comment]
> We have had the discussion before. We need a different layout manager/paradigm and that's a lot of work. Enough work, it might be easier to start from scratch and not call it Shoes. or Use wx-wdiget with a nicer ruby dsl.

How about we open an issue for this? Not something to be done anytime soon and perhaps never but talking may get us somewhere along the road. I am interested in your view and take on the subject. Besides, the current layout manager is somehow poorly understood (and not properly documented). I just now realize Shoes arts are always using absolute position... after 3 years using Shoes.

**Comment by ccoupe** [comment]
OSX is sufficiently difficult about changing the height of buttons that I'm going to not attempt it.  A high amount of work  with no demand and it looks ugly on Gtk3 and uglier on OSX - should it work and it doesn't.

**Comment by ccoupe** [comment]
Major Progress on this issue: Edit_line, edit_box (gtk)

![gtk-editline](https://user-images.githubusercontent.com/222691/35551855-5f5faff4-054e-11e8-9fae-721633f916ad.png) 
![gtk-editbox](https://user-images.githubusercontent.com/222691/35551991-114cc42c-054f-11e8-9cc4-9cf334a43559.png)

list_box, switch: on Gtk 
![gtk3-listbox](https://user-images.githubusercontent.com/222691/35552293-95c84cb6-0550-11e8-898a-01c70739a27f.png)
![gtk3-switch](https://user-images.githubusercontent.com/222691/35552683-1593977e-0552-11e8-8bc0-c610e556820b.png)

OSX it  a bit different but acceptable.

**Comment by dredknight** [comment]
This is awesome!

**Comment by ccoupe** [comment]
@dredknight , there is a [Windows beta](https://walkabout.mvmanila.com/public/shoes/shoes-3.3.6-gtk3-32.exe) if you want to play with it.

**Comment by ccoupe** [comment]
OSX is equal to Gtk 
edit_line
![osx-editline](https://user-images.githubusercontent.com/222691/35608745-aa025362-0617-11e8-90a5-983e4727d93e.png)
edit_box
![osx-editbox](https://user-images.githubusercontent.com/222691/35608921-8beae41a-0618-11e8-9b2c-5ef61ee095f2.png)
list_box 
![osx-listbox](https://user-images.githubusercontent.com/222691/35609093-390df6b4-0619-11e8-90eb-c2fa78fb3172.png)
switch:
![osx-switch](https://user-images.githubusercontent.com/222691/35609224-bdf8bc88-0619-11e8-9b14-dfcaea74327c.png)
button: 
![osx-button](https://user-images.githubusercontent.com/222691/35609367-3c98b408-061a-11e8-951a-d108d42c5733.png
As the manual says,  button height doesn't work on OSX.

**Comment by dredknight** [comment]
Definitely something that will be used for the next skillwheel update!
