### ISSUE TITLE
Scrollbar is not moved when maximizing window

### ISSUE THREAD

**Issue by BackOrder** [shoes/shoes3#349]
![image](https://cloud.githubusercontent.com/assets/8844578/24564693/c99145f4-1620-11e7-9f7c-ad04da2b870a.png)

**Comment by BackOrder** [comment]
May be related to #38.

**Comment by ccoupe** [comment]
Not related to #38.  Many problems, all platforms, some different.

**Comment by ccoupe** [comment]
Update: When you've stared at the code and instrumented it and nothing makes sense then remember - uses a start block. That fixed my problem.  I can get @BackOrder problem sometimes. And sometimes the scrollbar is drawn to the left of window by 5 pixels of so. Hmm,. there was another problem with backgrounds appearing.

**Comment by ccoupe** [comment]
Fixed in Shoes 3.3.7
