### ISSUE TITLE
Shoes Windows could have themes

### ISSUE THREAD

**Issue by ccoupe** [shoes/shoes3#354]
Continued from #345

One problem with having the user download and switch themes is that Windows wants Admin rights to wrire into Common Files (x86). Fortunately, Gtk has some not well known/documented ways to find settings.ini

If you create %USER%%APPDATA%\Local\gtk-3\settings.ini that it will override any previous setting found during gtk initialization. I tried it. It works. Now, we need a place to store the user supplied/downloaded themes so GTK can find them and of course GTK has many options for doing that., also not well documented for Windows.I just need to find one that is user writeable.

**Comment by ccoupe** [comment]
Many Gtk themes will work so-so with Shoes and some not at all. From the shoes perspective, they are bloated with lots of things Shoes/Windows doesn't need and can't use so it is problematic to make it Shoes easy.

**Comment by ccoupe** [comment]
see [wiki](https://github.com/Shoes3/shoes3/wiki/Changing-Gtk-theme-on-Windows)

**Comment by dredknight** [comment]
Splendid!

**Comment by ccoupe** [comment]
This will be fun for the curious. It's only working on Linux (so far). The first image is my default theme. The second image is from a Gtk3 Theme named XP
![theme-default-combo](https://user-images.githubusercontent.com/222691/39676608-e2dd467a-512a-11e8-9946-72a16283cdc8.png)
![theme-xp-combo](https://user-images.githubusercontent.com/222691/39676612-eb9d62f4-512a-11e8-9ae9-769d05e7c152.png)

You need a Gtk3 theme without ties to different theme engines. For example, the FlatStudio theme is tied to the `unico` theme engire and doesn't work with Shoes (on my Linux system)

**Comment by ccoupe** [comment]
Switching theme is pretty simple.
![theme-switch](https://user-images.githubusercontent.com/222691/39678229-e007e5f2-5145-11e8-9ecb-002f0c78017c.png)
The real problem is that most of the Gtk3 themes I've tried have failed to parse. Since I have no css skills that's going to slow progress.

**Comment by ccoupe** [comment]
I've got 3.3.7 betas for Windows, Linux X86 and freebsd that will load a theme from ~/.shoes/themes Appdata/Local/Shoes/themes for Windows. Note: That's a user writable space. You'll want a theme that works[ like XP](https://walkabout.mvmanila.com/public/share/XP.tgz) Untar it , create the above directory and move the XP directory to it. Cobbler->Theme->Switch should finds it. Save. Restart Shoes. If you launch from the terminal you'll get a message that it load the theme.Or if you add a poor theme to the directory, you'll get screen or two of parsing errors to fix. 

That about the end of what I can do. Somebody else can deal with bad css.

**Comment by ccoupe** [comment]
Closing 3.3.7 issues.
