### ISSUE TITLE
After and Before does not accept arguments correctly? No example in the manual

### ISSUE THREAD

**Issue by dredknight** [shoes/shoes3#359]
Dear everyone,

I try to execute this code that introduces new element inbetween other elements but it does not work.

```Ruby
Shoes.app do

	@my_stack = stack do
		background yellow
		para 'number 1'
		para 'number 2'
		para 'number 3'
		para 'number 4'
		para 'number 5'
	end

	before(@my_stack.contents[2] ) do
		para 'number 1.5'
	end
end
```

What do I do wrong? there is no example in the manual so I am not sure if I do this correctly.
Cheers

**Comment by ccoupe** [comment]
I can think of many things to try. ^;)  I suspect you want `@mystack.before(@my_stack.contents[2] ...` because the before call has 'self' set to Shoes.app and not @my_stack.

**Comment by ccoupe** [comment]
It could also be that you need a  start {} proc on @my_stack or Shoes.app so that it runs after all the GUI context is established.

**Comment by dredknight** [comment]
This is not related to start, stop elements.

Adding **start** to  **mystack** gives error "contents for unknown element" because in that case **mystack** is initiated after **before**.

The other way around (start in front of before) is executed properly but the result is the same as above.
I believe that under the hood **after/before** work for reassigning elements between slots only.

**Comment by ccoupe** [comment]
This works for me. 

```ruby
Shoes.app do
	@my_stack = stack do
		background yellow
		para 'number 1'
		para 'number 2'
		para 'number 3'
		para 'number 4'
		para 'number 5'
	end
       @my_stack.before(@my_stack.contents[2] ) do
		para 'number 1.5'
	end
end
```
![pict359](https://user-images.githubusercontent.com/222691/27566939-b392c1c8-5aa5-11e7-9df6-fba08a417698.png)

**Comment by dredknight** [comment]
ahaaaaaaa I never thought it should work like this. this will do.
I will leave this thread open so I can add some guide improvements. 

Cheers. :)

**Comment by ccoupe** [comment]
Shoes.app {} is a slot. When a slot (flow or stack) is created the ruby 'self' is changed to be inside the block. Your  code was calling the' before' method of Shoes.app,  **not** the before method for object @my_stack.  It is confusing. The manual does describe this behavior but it's not newbie apparent, assuming they even read the whole manual.

**Comment by dredknight** [comment]
hahaha thank you. I will revise it for better transparency on those matters if you dont mind :)

**Comment by dredknight** [comment]
More descriptive information is added to the manual. I will initiate a pull request.

![image](https://user-images.githubusercontent.com/12410314/39750355-accab9fc-52bd-11e8-8381-a152917fe896.png)
![image](https://user-images.githubusercontent.com/12410314/39750370-b465c76a-52bd-11e8-9c1b-5b86060150bf.png)

**Comment by dredknight** [comment]
Thank you @ccoupe  :).
Closing this one.
