### ISSUE TITLE
edit_line and edit_box swallows keypress events

### ISSUE THREAD

**Issue by BackOrder** [shoes/shoes3#36]
Both **edit_line** and **edit_box** does not allow keypress events. It is not possible to handle keypress within an edit_line or edit_box once it is focused and the Shoes.app keypress event is ignore once the focus is on either one.

**TEST SCENARIO**
- Run the script below
- Type few keys, alt-keys, etc.
- Check the keys are displayed
- Click on the edit line
- Type few keys, alt-keys, etc.

**_EXPECTED RESULT**_ the keys should pass through keypress, as it does on Windows.

``` ruby
Shoes.app {
   edit_line
   keypress { |n| para n }
}
```

**Comment by ccoupe** [comment]
The cocoa.m:350 code to handle ShoesTextField is very short and just handles the case of a change in the edit_line/box. The keydown code is at line 188 and hints at what has to be done to emulate the Gtk2 behavior of sending keystrokes to both the widget and the keypress()

**Comment by ccoupe** [comment]
There are shoes_app_keypress() and shoes_app_keydown(). Gtk calls them both for GDK_PRESS event. OSX only calls _shoes_app_keypress().  

Some alt-key sequences are legitimately part of Apples text editing - including alt-left and alt-right( ! ) and as long as that edit box has OSX focus,  OSX does what OSX does.

**Comment by BackOrder** [comment]
> Some alt-key sequences are legitimately part of Apples text editing - including alt-left and alt-right( ! ) and as long as that edit box has OSX focus, OSX does what OSX does.

This is a useful piece of information. A simple test revealed that the whole edit_box and edit_line behaviour, including with the new keypress handling, is actually normal on MacOS X.

**TEST SCENARIO**
* Open Safari.
* Go to a page, then http://www.google.ca/, than another page.
* cmd-left to go back to http://www.google.ca/.
* Focus on the input box.
* cmd-left or cmd-right to go back or forward.

***ACTUAL RESULT*** cmd-left and cmd-right doesn't work either on Safari.

**Comment by ccoupe** [comment]
Helpful indeed. Fighting Apple's choices for cocoa is not a good practice for us.

**Comment by ccoupe** [comment]
I'm closing this report since it's probably not something we should be doing.

**Comment by ccoupe** [comment]
I'm closing this one. By definition keys for edit_line and edit_blocks belong to the native widget and processed by the Shoes change block - assuming you have one attached to the shoes widget. You can use the 3.3.5 event abilities to get if front of that if you really need that.
