### ISSUE TITLE
How to re-open a closed Shoes.terminal?

### ISSUE THREAD

**Issue by spachner** [shoes/shoes3#366]
Hi,

in case the user has closed the Shoes.terminal, how to re-open them again?

regards

spachner

**Comment by ccoupe** [comment]
Apologies @spachner . I commented early on many days ago  but it seems to have disappeared. Terminal vs Console ?  alt-/ or fan-/ on osx will reopen the Console. 

It is not possible, **cross-platform**, to re-open a Shoes.terminal. We had to do some very ugly things to get stderr and stdout redirected to it.  Some people want Shoes to halt when the Terminal is closed and some want it to not be close-able -  Windows  the is least common denominator  and Shoes/Windows  can't stop the user from closing of that window or even know that it happened.
