### ISSUE TITLE
Gtk 3.20.0 issues

### ISSUE THREAD

**Issue by ccoupe** [shoes/shoes3#369]
The freebsd port brought some loud an numerous warning messages on stderr.  The numerous (overwhelming) GTK warnings started in Gtk 3.20.0 and supposedly there is a patch that some linux/bsd distributions may or may not apply in a timely manner. Gtk 3 actively discourages pixel counting layout like Shoes does in favor of their own container/constraint layout manager scheme. (OSX/Cocoa encourages this too).

You can send them off to `.../shoes  2>/dev/null` but that defeats to purpose of having a command line. Of course if you start from the Menu, you'll never the warnings. 

It does not appear to be something **Shoes** can fix easily (or ever?).  This issue is filed for the future.

**Comment by BackOrder** [comment]
You might enjoy reading [Migrating from GTK+ 2.x to GTK+ 3](https://developer.gnome.org/gtk3/stable/gtk-migrating-2-to-3.html) manual.

**Comment by ccoupe** [comment]
I'm moving this to high priority because Shoes _as we know it_ now, won't be fun for anyone to develop on. Fix it now or give up. One day I'll upgrade to a Linux/Gtk3 that has this problem. I've created a branch of 'master' called 'subclass' .

**Comment by ccoupe** [comment]
I'm getting a sense of the problem. GtkButton can be (is a container for our purposes). gtkbuttonalt.c doesn't do the needed gtk size protocols for children/containers.

**Comment by BackOrder** [comment]
> I'm getting a sense of the problem. GtkButton can be (is a container for our purposes). gtkbuttonalt.c doesn't do the needed gtk size protocols for children/containers.

I did seem obvious when I suggested to removed the custom preferred width/height. It's not doing it right and thus causing warnings.

**Comment by BackOrder** [comment]
The GTK code in Shoes would certainly benefit from peer review. I'd like to invite @memnoth to join **Shoes3**. He is a Gnome programmer from Korea. Perhaps a warm welcome will tempt him to join us... :) :) :)

**Comment by memnoth** [comment]
It would be great idea to join. By the way, I need to take times to get to know this project. :)

**Comment by BackOrder** [comment]
> It would be great idea to join. By the way, I need to take times to get to know this project. :)

So good to have you here @memnoth ! I am willing to help you out with "the getting to know" part. Got the feeling that a fast start will make you unstoppable. :)

**Comment by ccoupe** [comment]
I'm giving serious consideration to how to get gtk2 back into Shoes.  I just ran into a Theme bug on the Raspberry Pi (PiX theme) that shows how unstable gtl3 is - lots of unfinished work wot go around.  Gtk2 could be a big task but it might be worth it. Thoughts?

**Comment by ccoupe** [comment]
I also read on the Gtk blog that 3.24 will be the last of the 3 series and from their perspective, they are done breaking things in 3.x and moving onto Gtk 4 (in 2019)

**Comment by ccoupe** [comment]
Closing 3.3.7 issues.
