### ISSUE TITLE
OSX installation

### ISSUE THREAD

**Issue by sjernigan** [shoes/shoes3#376]
Two issues.  First is minor.  The documentation (manual) says the installation on OSX is via a dmg but the download is a tgz.  No dmg to be found.

Second, when I download the tgz and unzip it. Something is off with the permissions.  When I attempt to start it (via the command line) LSOpenURLsWithRole() failed for the application <path>/Shoes.app/Contents/MacOS/../../../Shoes.app with error -10810.

From googling, it seems 10810 has something to do with either process limits or executable permissions.    I have ruled out process limits.  I have gone through the modal allowing applications for third party developers.  I have run 'sudo xattr -dr com.apple.quarantine Shoes.app/' in an attempt to do the same.  

This machine is a new install of High Sierra on MacBook Air.

**Comment by ccoupe** [comment]
Thanks for mentioning the error in the manual.  Shoes and the command line are a pain in OSX. If you get the Shoes splash screen, select Maintain Shoes and then Create cshoes - it will build a bash script name 'cshoes' that makes it easier for command line work.  Note the script has the hard coded location of the Shoes that build it so Shoes can't be moved or the script will fail.  But easy enough to recreate if you do move Shoes. There's nothing particularly magical about the bash script - but it does  deal with what most command line folks want without have to deal with the 'open' command mysteries.

**Comment by sjernigan** [comment]
Sorry.  I wasn't clear.  The app won't start with either the command line or the GUI.  I was able to install it on another air and another macbook pro without issues, neither with High Sierra.  Perhaps I'll give it a try on a forth to see if I can find a pattern.

**Comment by ccoupe** [comment]
Shoes was written to be 10.9 compatible, I'm on 10.10 and can't test any higher than that. It is certainly possible that newer versions changed something. Permissions for download apps is my first guess.

**Comment by spachner** [comment]
I was working all the day with MacOS 10.12.6 with Shoes3.3 for month. I further developed my app regarding yaml files and found problems in that area, GUI was still fine. So I tried Shoes4 which works also fine also with yaml file handling.

For reference https://github.com/spachner/mcmd

spachner

**Comment by ccoupe** [comment]
Thanks @spachner for confirming Shoes 3.3 probably does work on newer OSX than mine. Are you using 3.3.3? or something earlier? (Maintain Shoes ->Info button).

**Comment by ccoupe** [comment]
> Second, when I download the tgz and unzip it. Something is off with the permissions. When I attempt to start it (via the command line) LSOpenURLsWithRole() failed for the application /Shoes.app/Contents/MacOS/../../../Shoes.app with error -10810.

Did you really want to install it in "/"  instead of /Applications ? The '/Shoes.app' should be denied.

**Comment by spachner** [comment]
I used the 3.3.3 version, which worked, except the yaml stuff and switched then to Shoes4

**Comment by ccoupe** [comment]
Thanks for the 3.3.3 confirmation @spachner . Re: yaml - it's entirely possible that Shoes 3 includes a older yaml than shoes 4. libyaml 1.6 vs 1.7?

**Comment by sjernigan** [comment]
Unfortunately, I gave that machine away.  I didn't notice the /Shoes.app in the path and that could have been the problem.  Sorry for the delay, I'll repost when I get access to the troublesome machine again.

**Comment by Jefferson-Faseler** [comment]
I am also having the same issue. Which is really sad to me because I just replaced an old computer and wanted to work on some Shoes apps again. 

Attempted a few suggestions related to 10810 errors without any luck. [This](http://www.thexlab.com/faqs/error-10810.html) explains the error code.

**Comment by ccoupe** [comment]
@Jefferson-Faseler  - thanks for the historical link for 10810 errors. I need to study it in more detail.  My _suspicion_ is that Shoes has a very old plist structure in the Shoes.app. It's probably missing some new setting that 10.13.2 insists on. If it demands a code signing certificate the, my guess, then  Shoes/OSX has dim future - I am not not going to pay the high annual fees for an Apple Cert and a Windows Cert. What you and other 10.13.2 folks have to  explore is how to white list *.mvmanila.com as a trusted download source.  Windows 10 has similar problems in certain situations and it makes _business sense_ for  MSFT and AAPL to keep you from downloading and running apps.

**Comment by ccoupe** [comment]
More background [https://en.wikipedia.org/wiki/Gatekeeper_(macOS)](wikipedial)

**Comment by ccoupe** [comment]
As a last resort, you could build shoes from source, a particularly difficult task for osx.

**Comment by sjernigan** [comment]
Sorry for the delay.  I tried installing again on another High Sierra macbook air.  Same result.  I can't find a way around it.  So I'm purposefully not upgrading two laptops for fear they will stop working.  Has anybody tried upgrading a mac with a working Shoes install?  Does it still work?

**Comment by ccoupe** [comment]
You may be able to get some additional information by launching the console app, clear it and then try to launch Shoes. Then check the console window and see if there is anything proceeding the 10810 error and of course expanding the 10810 message. 

Here is something someone could try, this is my `cshoes` launch script that I use for command line work with OSX shoes . 
```sh
#!/bin/sh
# next two lines generated
APPPATH="/Users/ccoupe/build/xmavericks/Shoes.app/Contents/MacOS"
SHOES_RUBY_ARCH="x86_64-darwin14"
THISDIR=`pwd`
FLAGS=""
SCRIPT=""
OPTIND=1
if [ $# -gt 1 ] && ([ $1="--ruby" ] || [ $1='-g' ] || [ $1='--gem' ]) ; then
  FLAGS=$@
else
  while getopts "w:f:e:dghvcpm" opt; do
    case "$opt" in
    h) FLAGS="-h" ;;
    v) FLAGS="-v" ;;
    c) FLAGS="-c" ;;
    p) FLAGS='-p' ;;
    d) FLAGS='-d' ;;
    m) FLAGS='-m' ;;
    w) SCRIPT=$OPTARG; FLAGS="-w" ;;
    f) SCRIPT=$OPTARG; FLAGS="-f" ;;
    e) SCRIPT=$OPTARG; FLAGS="-e" ;;
    esac
  done
  shift $((OPTIND-1))
  if [[ -n $1 ]]; then
    #echo "found " $1
    SCRIPT=$1
    #if [[ -z $FLAGS ]] ; then
    #  FLAGS='-f'  # consider this a hack until shoes.rb is fixed for OSX
    #fi
  fi
  if [[ -n $SCRIPT ]] && (! [[ $SCRIPT =~ ^/.* ]]); then
    SCRIPT="$THISDIR/$SCRIPT"
  fi
fi
#echo "using shoes-bin $FLAGS $SCRIPT" 
unset DYLD_LIBRARY_PATH
DYLD_LIBRARY_PATH="$APPPATH" PANGO_RC_FILE="$APPPATH/pangorc" SHOES_RUBY_ARCH="$SHOES_RUBY_ARCH" $APPPATH/shoes-bin --osx $FLAGS $SCRIPT
```
You'll have to  edit the APPPATH in line 3 to match where your Shoes.app lives - keep the `Shoes.app/Contents/MacOS` at the end.  You'll need to `$ chmod +x cshoes` to make it runnable. The cshoes script bypasses most of launch services. I bet it will work (or provide more useful error messages). Either way it would narrow down the problem.

**Comment by ccoupe** [comment]
See #383.  No need to do the cshoes test unless you want to confirm,

**Comment by ccoupe** [comment]
See #398  - That would be my likely culprit - libz moves/changes . Can any body else confirm that
Dyld error message in their core dump. 

This is also a potential [issue/solution](https://www.oxygenxml.com/forum/topic13639.html)

**Comment by ccoupe** [comment]
I've got a [beta for High Sierra](https://walkabout.mvmanila.com/public/shoes/shoes-3.3.5-osx-10.10.tgz) users to try. Please give it a try and report back. It works on 10.10 and hopefully up to 10.13.

**Comment by dippersauce** [comment]
I was able to make Shoes work by deleting libs.1.dylib for the Shoes.app. I'll try the beta you posted in a while and see if that fixes the issues.

**Comment by ccoupe** [comment]
@blswchrobry  - please try the [beta mentioned](https://walkabout.mvmanila.com/public/shoes/shoes-3.3.5-osx-10.10.tgz) above

**Comment by blswchrobry** [comment]
The beta works too.

**Comment by sjernigan** [comment]
Just confirming that the Shoes 3.3.5 OSX install installs fine on High Sierra.  Sorry for the delay, Thanks!
