### ISSUE TITLE
Grey out check box?

### ISSUE THREAD

**Issue by Dassadar** [shoes/shoes3#381]
Hello,
Is it possible to grey out a check box please?
Thx & regards,
Dassadar

**Comment by BackOrder** [comment]
Long time no see @Dassadar ! 

Normally a simple `check state: "disable"` would do but state is not working on FreeBSD. Perhaps it would fare better on your side?

Remember to join our new Facebook page!
https://www.facebook.com/rubyshoes3/

**Comment by BackOrder** [comment]
oops, typo.

`check state: "disabled"` should work.

**Comment by BackOrder** [comment]
@ccoupe I'm getting the following errors in Shoes Console when using state parameter. Seems to be only affecting check.

```
Error in <unknown> line 0 | 2017-11-01 18:37:35 -0400
control can't have :state of disable


Error in <unknown> line 0 | 2017-11-01 18:37:44 -0400
control can't have :state of disable

```

**Comment by Dassadar** [comment]
It works for me, thx! 
Indeed, long time no see :-)
I'm currently redesigning my app!

**Comment by BackOrder** [comment]
Good to see you again. :)

> I'm currently redesigning my app!

We are looking to showcase Shoes on Facebook and possibly the main website. You could perhaps share screenshots and video later on, if you would like. Any help would be good.

**Comment by Dassadar** [comment]
I could share the previous version folder with you on google drive?

**Comment by BackOrder** [comment]
Sure!

**Comment by Dassadar** [comment]
on which mail address? or else PM?

**Comment by BackOrder** [comment]
There is no PM on Github. You can PM on the Facebook page. Either @dredknight @ccoupe or I will see it.

**Comment by Dassadar** [comment]
not sure to see where... just send me a PM on facebook "David Pauchet"

**Comment by BackOrder** [comment]
About a dozen of you guys. Which avatar do you have on Facebook?

**Comment by Dassadar** [comment]
green background, "upr" logo

**Comment by BackOrder** [comment]
Je t'ai envoyé un message. :)
