### ISSUE TITLE
Debugging code ?

### ISSUE THREAD

**Issue by dredknight** [shoes/shoes3#382]
Hello everyone,

I was wondering what are you using (and what is available to Shoes) to debug shoes code/scripts?
Something I bumped into is "pry" gem but I do not know if it is supported by shoes.

**Comment by ccoupe** [comment]
Shoes has byebug built in. https://github.com/Shoes3/shoes3/wiki/Debugging-with-Byebug

**Comment by dredknight** [comment]
Thanks @ccoupe ! I will leave this thread open for a few days in case I totally fail with how it works.

**Comment by dredknight** [comment]
Got it :)
