### ISSUE TITLE
Shoes to use html colour codes?

### ISSUE THREAD

**Issue by dredknight** [shoes/shoes3#386]
Is it possible Shoes to use HTML colour coding?

For example I have a file with the following text: 
**Adds +1 to the Hero's four primary attributes and increases initiative of all shooters in Hero's army by 10%<br><br><color=purple>Power of Dragons (1/8)<color=white><br>The hero is granted +4 in every primary skill for wearing the full Dragon armor. Half of the pieces gives +2 in every primary skill.<br><br><color=orange>Quest<color=white><br>Bring all 8 pieces of the Dragon armor to a Sacrificial Altar and receive a unique reward.**

can I use the HTML syntax to make the text align and colour itself instead of doing it myself?

**Comment by BackOrder** [comment]
Have you considered using Shoes internal markup? The manual is written in that markup language. You could also parse the colours by yourself and render it in Shoes. I did something like that and it gave birth to [Shoes eBook](https://github.com/Shoes3/ebook). Shoes eBook is work in progress but that would be nice on the Facebook page #380. Same goes for screenshots of the manual.

**Comment by dredknight** [comment]
@BackOrder I would go with Shoes parser style any day but I am not writing the text. It is extracted as is from batch of files and just migrated to the Skillwheel. It is not that bad if it is not possible I will have to write my own HTML parser to convert the text into the style the Skillwheel app supports.

I will make something for FB :).

**Comment by BackOrder** [comment]
[Nokogiri](http://www.nokogiri.org/) gem is installed by default in Shoes. It will make your life easier for parsing texts and collect attributes to apply Shoes related colouring.

**Comment by dredknight** [comment]
gosh.. I am using nokogiri extensively for XML parsing but I did not think it can be used for HTML too.
Thank you @BackOrder  :)
