### ISSUE TITLE
Flow + radio + clear breaks shoes

### ISSUE THREAD

**Issue by dredknight** [shoes/shoes3#391]
I managed to break Shoes (3.3.5 r3080) again. If you launch the code below and click the button it will break. I found 2 fixes -  Commenting the flow line + end line or commenting the radio line.

```Ruby
Shoes.app do
	def main slot, stuff
		slot.clear do
			stuff.each_with_index do |x, i|
				flow do                             ####### FIX 1 : COMMENT THIS LINE 
					radio :item;          ####### FIX 2 : COMMENT THIS LINE 
				end                                   ####### FIX 1 : COMMENT THIS LINE 
			end
		end
	end
	
	ITEMS = Array.new( 10, 1 )
	desktop = stack left: 20, top: 40, width: 200 #do
	main desktop, ITEMS
	button "Reset" do
		main  desktop, ITEMS
	end
end
```

**Comment by BackOrder** [comment]
This is a curiosity indeed. Clicking on reset lit up all the radio buttons. Did you try this with other widgets?

FIX 2 is kinda funny. Doesn't make much sense. :)

By the way, I removed the \** because bold cannot be used in code.

**Comment by dredknight** [comment]
What do you mean lit them up? When I click reset I get runtime error :/

![image](https://user-images.githubusercontent.com/12410314/33232792-f3056248-d214-11e7-9f3d-92dcbd55507f.png)

**Comment by BackOrder** [comment]
You should have specified earlier. Anyway, this is what I get after clicking on reset on FreeBSD:

![image](https://user-images.githubusercontent.com/8844578/33232800-66bca646-d1da-11e7-9797-0c43b01aba6c.png)

**Comment by dredknight** [comment]
At least we know it is Windows related :)

**Comment by BackOrder** [comment]
It's not supposed to lit up all the radios either! So it affects us all.

**Comment by dredknight** [comment]
Agreed :)

**Comment by ccoupe** [comment]
There is a sequence of Gtk error messages after I push the button:
```sh
(shoes:24321): Gtk-CRITICAL **: gtk_radio_button_get_group: assertion 'GTK_IS_RADIO_BUTTON (radio_button)' failed
```
Critical is usually a serious problem worth fixing. I'm guessing that the problem is the radio group :items is not cleared/deleted

**Comment by dredknight** [comment]
Can I do something to help you finding the root cause?

**Comment by ccoupe** [comment]
> Can I do something to help you finding the root cause?

Not yet. The sample code above is very helpful - thank you. I suspect part of the problem is that the 'group' list is supposed to be at the app level but appears to be done at the canvas level. This is likely to be a very old bug in Shoes - 7 or 8 years old.

**Comment by ccoupe** [comment]
We do have a confusing spec.  The way I interpret the Manual and the code,  radio groups do **not** belong to a stack/flow - they belong to the App/Window. So, clearing the slot as done in the example will not/should not clear a radio group.  

It's also true that shoes_canvas_clear() will attempt to clear radio groups - it probably shouldn't  (and gtk complains when it does). For fun, there's also code being called that does nothing useful. This is going to take some thinking and possibly and api change to Shoes

**Comment by ccoupe** [comment]
I've got a partial fix for the problem - you can get a windows beta at the usual place if you really want one - there are other radio problems. Use bugs/bug391.rb to test. - use code 'run this' code in the manual to find more problems

I've always had problems with how Shoes does radio buttons and revisiting the code  just enforces my option that it's a bodge. After my latest visit to the hospital, I don't have a lot of mental stamina. Getting better, but it's taking it's sweet time.
