### ISSUE TITLE
Disable events for all elements in a slot?

### ISSUE THREAD

**Issue by dredknight** [shoes/shoes3#393]
Hello everyone,

I was wondering if there is a nifty way to disable events (hover, click etc..) for all elements in one slot.
Example situation  - Hide a slot and its elements behind another slot covered in color.

Currently when this is done events are still detected.
![image](https://user-images.githubusercontent.com/12410314/33321440-634b728c-d44e-11e7-8460-b2a52c6f3190.png)

![image](https://user-images.githubusercontent.com/12410314/33321427-5165853a-d44e-11e7-8ad3-c7743a12d54a.png)

**Comment by BackOrder** [comment]
There are two ways to do this. The classic way to do this is to use a `@variable` to enable and disable the code within your click event. I use a similar technique in Numinoes: simple, fast and effective. The second way is to override the click event. 

Number One:
```ruby
Shoes.app do
   stack do
      image "#{DIR}/static/shoes-icon.png"
      click do
         if @clickable
            para "hey"
         end
      end
   end

   button "enable" do
      @clickable = true
   end

   button "disable" do
      @clickable = false
   end

   start do
      @clickable = true
   end
end
```

Number Two:
```ruby
Shoes.app do
   @b = proc do
      para "hey"
   end

   @s = stack do
      image "#{DIR}/static/shoes-icon.png"
      click &@b
   end

   button "enable" do
      @s.click &@b
   end

   button "disable" do
      @s.click do; end
   end
end
```

**Comment by dredknight** [comment]
Very interesting! I believe method 1 is better when it comes to hundreds of elements.
All image events in the wheel are defined by this block here:
```Ruby
def set	(img, options={}, &block )
	img.hover { @hovers.show text: options[:text], header: options[:header] , size: 9,  text2: options[:text2], width: options[:width], height: options[:height]; img.scale 1.25, 1.25 }
	img.leave { @hovers.hide; img.scale 0.8, 0.8 }
	img.click { @hovers.hide; block.call if block_given? } 
end
```
I just have to add a the @variable thing inside and we are ready to go. 
Thank you @BackOrder !

Just out of curiosity I was wondering of this is able to be embedded in Shoes on per slot basis. For example this will disable all events for the slot and all children, grandchildren (and so on) .

```Ruby
Shoes.app do
   @slot = stack do
      image "#{DIR}/static/shoes-icon.png"
      click do
         if @clickable
            para "hey"
         end
      end
   end

@slot.events "disable"
```

It just popped into my mind as a pragmatic solution but I can't tell how hard if it can be integrated in shoes at all (or is it easy to do).

Cheers!

**Comment by BackOrder** [comment]
> Very interesting! I believe method 1 is better when it comes to hundreds of elements.

You are correct. As little as 64 stacks in Numinoes were enough to give hard time to Shoes. So I came up with several very clever ways to simplify the thing. Maybe I should open source Numinoes and write an eBook #213 if that ever happens. :)

> RE: `@slot.events "disable"`

It sounds like something that would belong to #383. Be assured that generally speaking you do not need that. Once again there are many ways to do that (including traversing the slot to find and disable events) but a simple `@variable` would do. In Numinoes, there is an `@array` (8x8, 64 items) holding several states including **clickable**. 

You may just have a slot specific variable `@slot_dark_magic_clickable` and every event in the slot and its children should check for `if @slot_dark_magic_clickable`. Repeat with different variable names for other **main** slots that need to be enabled/disable independently.

Remember, branching conditions such as `if` are very low cost in programming!

**Comment by BackOrder** [comment]
Alternatively, you could also use a `Hash` for a single variable `@clickable` if you have several slots to enable and disable independently. Then you can use it as `@clickable[:dark_magic]`, `@clickable[:white_magic]`, etc. with `true/false` values.

**Comment by dredknight** [comment]
Thanks! I guess it comes down to writing a meta code for a meta code. Exactly what I like doing xD.

**Comment by dredknight** [comment]
Maaaaan it took just 10 mins of work to implement an area based solution across the whole app. Shoes is the best! 🏅

**Comment by BackOrder** [comment]
> Maaaaan it took just 10 mins of work to implement an area based solution across the whole app. Shoes is the best! :medal_sports:

Fantastic! By the way, it would be really nice to document these two techniques on the Shoes wiki. If you wouldn't mind. :)

**Comment by dredknight** [comment]
Will do! Actually I was thinking to combine the Facebook and github wiki thing to compliment each other.
FB will spread the word about things that are in the wiki.

**Comment by dredknight** [comment]
@BackOrder  here is the first iteration of the guide.
https://github.com/shoes/shoes3/wiki/Managing-events-on-a-global-scale

**Comment by BackOrder** [comment]
@dredknight excellent, you did very well. Contributed tips is appropriate.

> RE: `@event_disabler`

The name is misleading because when you set it to true, it means **disable the event**. So it should be named `@event_enabled` instead considering that you are testing true to enable a given event.

> RE: code examples

It would have been nice to keep the code snippet I posted above as they are simplifications in addition to what you presented there. Though I truly enjoyed your approach, intermediary Shoes users will find it absolutely satisfying. This is something we should keep doing in the future.

Overall great job!

**Comment by dredknight** [comment]
Sorry for not putting your code I just decided to write a guide and made it in one straight burst without thinking it too much. I will make better arrangements and fixes according to your proposals. 

One good idea is on each such tip article to put the least amount of code necessary on the top of it (your example) and below start making a concrete example (my example) which will explain to the user all the necessary phases  and add a bit on top.

Not sure I explained it very good but what do you think?

**Comment by BackOrder** [comment]
> Sorry for not putting your code I just decided to write a guide and made it in one straight burst without thinking it too much. I will make better arrangements and fixes according to your proposals.

No worries here. You did really well.

> One good idea is on each such tip article to put the least amount of code necessary on the top of it (your example) and below start making a concrete example (my example) which will explain to the user all the necessary phases and add a bit on top.
>
> Not sure I explained it very good but what do you think?

Yes, perhaps have an overview section and then proceed with the tutorial/guide.

**Comment by dredknight** [comment]
@BackOrder I did another edit on the article. Event_disabler is now called event_handler. Let me know if you have any more tips!

**Comment by BackOrder** [comment]
Thanks @dredknight.

> Let me know if you have any more tips!

How about the tip from #385 ?

**Comment by dredknight** [comment]
To make it into a guide? Alright I am pretty  hooked. But I gotta a question. that is going to be asked there.
