### ISSUE TITLE
Some links don't work

### ISSUE THREAD

**Issue by BackOrder** [shoes/shoes3#395]
**Manual > Furthermore > Internet**
- Shoes 3.2 Wiki
- Shoes 3.2 source code

Other links seem to work. May be FreeBSD only.
Feedback on other platforms?

**Comment by BackOrder** [comment]
The links above are HTTPS whereas others aren't.

**Comment by ccoupe** [comment]
No external links in the manual work for me.  I suspect the manual code that supports the link clicking is not using xdg-desktop methods. Of somewhere else in shoes doesn't.  I remember seeing two browser launch methods in the code and wondering who uses which.

**Comment by ccoupe** [comment]
@BackOrder is correct - it is the `https` string -  in help.rb:324 it is now
```
    elsif head =~ /^(http|https):\/\//
```
It works for me and makes sense - don't always get the easy ones.
