### ISSUE TITLE
Shoes 3.3.5 and deprecations

### ISSUE THREAD

**Issue by ccoupe** [shoes/shoes3#399]
Shoes 3.3.5 will not have a Linux Intel 32 bit build. Time to move on. Raspbian and Windows are still 32 bit. OSX 10.9 (Mavericks) might work but 10.10 (Yosemite) will be the  baseline for Shoes/OSX. Wait, it gets worse (or better) - Shoes/Linux will be built with libraries from Ubuntu 16.04 (LTS) instead of the very, very  old Debian 7.2 libraries. It's time to move to 2016.  I started Shoes maintenance in December of 2014. Since then, the platforms have move a lot and Shoes3 can't be relevant if it doesn't move with the platforms.

**Comment by BackOrder** [comment]
Makes sense and in line with our efforts to make Shoes easier to maintain.

> Shoes/Linux will be built with libraries from Ubuntu 16.04 (LTS) instead of the very, very old Debian 7.2 libraries.

Something interesting happened while we were working on #365 Running Shoes on FreeBSD. I was trying to use Linux compatibility using Ubuntu libraries as you had suggested but there were many hurdles. The libraries didn't play so well together and the endless number of libraries necessary was a burden. 

CentOS (7.x) might be a better choice than Ubuntu as it is more reliable and more likely to be compatible with any Linux ecosystem. I actually had Shoes running on FreeBSD using only a handful of CentOS libraries. Feedback for your consideration.

**Comment by ccoupe** [comment]
The only real differences in Linux distros **for our** purposes is the library version supplied and what and how many  commands we have to type. Ubuntu is down to 7 or 8 'apt-get install' to get a schroot working well enough to build and run Shoes. I dislike all package mangers equally but I do know some of the Debian/Ubuntu package names by heart and they are documented at the wiki. Ubuntu is easier for me and since I'm the only only one building an schroot .... I have enough Linux admin things to learn/remember [with the new hardware running Mint ](http://walkabout.mvmanila.com/2017/12/26/backups-are-useful/) and the 500GB SSD will be here on Tuesday so I'll  repeat some things.

**Comment by ccoupe** [comment]
OSX baseline is now 10.10 (Yosemite). I can still build 10.9 and I do, **but** they are different - 10.10 has more recent Ruby (2.3.6) and gem versions (byebug, and others). It's darwin14 instead of darwin13 and that really matters to Ruby - those are not _my_ rules.  There is a 74MB [download of 10.10 deps libs(https://shoes.mvmanila.com/public/shoesdeps/10.10.tgz)s

**Comment by ccoupe** [comment]
Closing. Priorities matter.
