### ISSUE TITLE
Para align misbehaviour

### ISSUE THREAD

**Issue by arjunmenon** [shoes/shoes3#402]
Hey
The para align property does not align elements, left and right, as expected
![screenshot from 2018-03-11 21 30 01](https://user-images.githubusercontent.com/953959/37255506-75e1dd16-2573-11e8-9d40-13f3be762e3a.jpeg)
Shouldn't the `right` align, push the para to the window edge?
Alternatively, using `right: 0` shoves it way past the window edge
![screenshot from 2018-03-11 21 35 39](https://user-images.githubusercontent.com/953959/37255558-2b6a2e04-2574-11e8-8152-e98f6f1e8083.jpeg)

```ruby
hash_items = {:apple => "fruit", :ball => "toy", "cat" => "animal", :dog => "animal", :egg => "food"}

Shoes.app(:title => "Shoes APp", :width => 350, :height => 500, :resizable => false) do	
	stack(margin: 10, width: "100%") do
		border black, strokewidth: 5
		hash_items.each do |k,v|
			flow do
				border red, strokewidth: 5
				para k, :align => "left"
				para v, :align => "right" # , :right => 0
			end
		end		
	end
end
```

_EDIT - on elementary 0.4.1, ubuntu 16.04_

**Comment by ccoupe** [comment]
There is a related? bug for Shoes 4 #1559 which looks like this in Shoes3 - this script,
```ruby
Shoes.app height: 200, width: 200 do
  stack do
    title 'Center', align: 'center'
    para 'Default'
    para 'Default'
    para 'right-aligned 1', align: 'right'
    para 'right-aligned 2', align: 'right'
    para 'left-aligned 1', align: 'left'
    para 'left-aligned 2', align: 'left'
    para 'centered 1', align: 'center'
    para 'centered 2', align: 'center'
  end
end
```
![bug402b](https://user-images.githubusercontent.com/222691/38212929-c4654e9a-367c-11e8-9ee4-cd673ce0997b.png)

**Comment by ccoupe** [comment]
The second example shows that right-align works for _text in the para_.  You can also comment the `#para k, align: "left"` and right is correct.  Shoes has a habit of merging para in some situations and I suspect that is what is happening here. This script almost gets it - flow is tricky when it overflows.
```ruby
hash_items = {:apple => "fruit", :ball => "toy", "cat" => "animal", :dog => "animal", :egg => "food"}

Shoes.app(:title => "Shoes APp", :width => 350, :height => 500 ) do
    stack(margin: 10, width: "100%") do
        border black, strokewidth: 5
        hash_items.each do |k,v|
            flow do
                border red, strokewidth: 5
                stack width: 200 do
                  para k, align: "left"
                end
                stack width: 100 do
                  para v, align: "right"
               end
            end
        end
    end
end
```

**Comment by arjunmenon** [comment]
This will do. Thanks,
