### ISSUE TITLE
ruby program (packaged with shoes) still needs installed shoes to run on windows?

### ISSUE THREAD

**Issue by bolandross** [shoes/shoes3#404]
Hey folks,

I noticed something odd on Windows 10 (64 Bit).

I just took a simple ruby shoes example from the shoes tutorial site and saved it as a .rb file. Then I installed shoes (the Win7 32 Bit installer) and chose "Package an App with Shoes".

On the next screen, I checked "Shoes will be included with my app.", selected Win32 as architecture and got the final .exe file in the end of the process.

I ran the program and everything worked as intended.

**Now the strange stuff:**
Since I was curious, I uninstalled shoes from the system to simulate the environment of the folks I'd like to give the packaged program to and double clicked the .exe file again.

No running program anymore. For a fraction of a second I can see a little program with a progress bar which says "Setting up Shoes..." and then I get an windows error which (translated) tells me that the App can't be executed on my computer and that I should consult the software publisher.

This defeats the purpose of packaging shoes /-: 

Any ideas?

Thanks for your time guys.

**Comment by ccoupe** [comment]
Sorry for the delay - health issues.  This is a well known issue with Windows 10 and can't be fixed without an expensive code signing certificate from MSFT. [There is a work around](https://github.com/Shoes3/exe-shoes) if you're are willing to do the work and suffer some. 

> This defeats the purpose of packaging shoes /-:

Yes, yes it does. Thanks to  MSFT.

**Comment by bolandross** [comment]
Hey, no problem!
Thanks for the explanation and for offering a workaround. This also might help people that encounter a similar problem.

Keep up the good work and get well soon.
Best regards
