### ISSUE TITLE
Reference parent window from child

### ISSUE THREAD

**Issue by arjunmenon** [shoes/shoes3#409]
Hey
How can we reference objects in the parent window from the child window?

```ruby
 Shoes.app title: "The Owner" do
   
   button "Pop up?" do
     window do
       para "Okay, popped up from #{owner}"
       @el = edit_line do |e|

		      para e.text+"\n"
		      @para.text = e.text
       end
	@el.finish = proc { |slf| para "enterkey #{slf.text}\n" }
     end
   end

   @para = para "replace"
 end
```
I get error
`undefined method text=' for nil:NilClass` at `@para.text = e.text`

I am sure there was a way to do this. But I can't find this in the docs.

Also, the button can open multiple instances of child windows. Can it be restricted to only one window with focus shifted to it until it is closed?
Basically I am trying to add a properties option to the menu which opens a window to change settings.

**Comment by ccoupe** [comment]
Welcome to the confusing world of 'app' and 'self' (and modules)  Each window or Shoes.app is an unique object of class Shoes. To be confusing, that is often called the 'app'. That means instance variables like @e1 and @para belong to the object (app) that created them - two different objects in your example. It's is mentioned in the manual but the implications are not obvious.   

What to do about it?  
1. You can create class variables like `@@para` and @@e1
2. You can use Ruby global variables like '$mydb`
3. You can cleverly navigate from one app to another and `instance eval' 

[This wiki article](https://github.com/shoes/shoes3/wiki/Poking-in-Shoes.app) discusses some ways to  navigate around.   **I** would  create a new ruby class 'properties, create the object  and  store it in $properties but that's just me and it's not without challenges of it's own.

> Can it be restricted to only one window with focus shifted to it until it is closed?

APPS is a constant that has an array of all open windows (aka apps). In `button "Pop Up" do` you could check APPS.length. If it is 1 - then create the window, if it's 2 then the window already exists.

**Comment by arjunmenon** [comment]
Yeah it's a bit hacky.
The problem is the child is in no way attached to the parent. So if the parent is closed, child still stays there.
I am doing this as a check on the child
```ruby
animate do 
        # check if APPS array has parent, else close
        Shoes.APPS[0].close if Shoes.APPS[0] != owner
end
```
This is way too hacky. I suppose a "normal" GUI keeps track of and manages its child windows, and shifts focus.

Is there a better way? I promise I remember a sample script which spawns a child window and they both communicate, with a button. I can't remember it where it was. I checked and double and tripled checked.

There should be one.

====

One another note, I am saving a file in the `tmp` directory after doing some file manipulation, basically when the user has done some file manipulation. 
To the user it feels like everything autosaves.
Now after they are done with, they can choose to save their work in their chosen folder. 

I can do `ask_open_folder` and do a system call like `cp /tmp/file_name /home/choosen_folder`

But I am not sure there is a SHOES method which allows to copy file from the `tmp` directory to their chosen folder. Is there?


How can we do it though?

====

More question 
1. Do Shoes allows gems having native bindings?
2. In the `url` demo, where we navigate to different pages, the above hack to communicate between child and parent does not work the same way between pages? Why and what better way is there?
3. Ability to add subtle animation effects when navigating pages with url, like fade or slide

====

No more questions. ;)

**Comment by ccoupe** [comment]
> This is way too hacky. I suppose a "normal" GUI keeps track of and manages its child windows, and shifts focus.

You are thinking of modal dialogs. Shoes does not have those. You have to design (not program but design) around that. @dredknight  may have some thoughts about this. Everyone has to deal with it. I favor a wizard or multi-panel approach instead of multiple windows. Also see the visit/url approach.

Temporary files, saved settings (and persistent datbases) is a platfrom problem. It's going to be different for Windows vs OSX/Linux.  ENV['APPDATA'] for Windows is the place to start. Shoes uses that to store user things  like downloaded gems.

> Do Shoes allows gems having native bindings?
Yes, BUT - On Linux and OSX you'll need the compilers and libraries. Gems often have Windows binaries but if they don't then Windows needs the compilers and that is a real pain.  Generally, If you can get a gem to install, then Shoes can included it with your app. There is a lot in the wiki  about gems.

> Ability to add subtle animation effects when navigating pages with url, like fade or slide

I am the wrong person to ask. I don't do pretty or effects. Others do and may have ideas.

**Comment by ccoupe** [comment]
> The visit/url approach does not work as intended. 

The vist/url screens share data stored in $globals **not** data stored in the GUI widgets. It works, It may not be pretty but it works..

> No easy way to refer objects in between.

There is no easy way to refer to **GUI Widgets** in different apps/windows - don't keep your data there. Truth be told, you can get to those widgets but it's not easy. You've got all of Ruby's abilities poke around

> essentially "downloading" the file to its folder.I am looking for this.

The download method has enough options to do this. No?

**Comment by dredknight** [comment]
@arjunmenon here you go buddy:

```ruby
Shoes.app title: "The Owner" do
   
	@child = nil 	# Variable for the new window
	
	button "Pop up?" do
		if not @child.nil? then  # if window exists close it, new one will be open
			@child.close
		end
		@child = window do
			@child_text = para "Okay, popped up from #{owner}"
			@el = edit_line do |e|
				  para e.text+"\n"
				  @child_text.text = e.text
			end
			@el.finish = proc { |slf| para "enterkey #{slf.text}\n" }
		end
    end
 end
```

Here is a bit more advanced version.
```Ruby
Shoes.app title: "The Owner" do
   
	@child = nil 	# Variable for the new window
	
	button "Pop up?" do
		if not @child.nil? then  # if window exists close it, new one will be open
			@child.close
		end
		@child = window do end
		@child_text = @child.para "Okay, popped up from #{@child.owner}"
		@el = @child.edit_line do |e|
		      @child.para e.text+"\n"
		      @child_text.text = e.text
		end
		@el.finish = proc { |slf| @child.para "enterkey #{slf.text}\n" }
    end
 end
```

Here is an advanced version that shows some flaws in Shoes ;(. 
Unless every single new element/behavior is explicitly forwarded to the child it remains on the master even when it is triggered in element that is on the child.

Some example lines from the code below:
````@child_text = @child.para "Okay, popped up from #{@**child.owner**}"
this will not work if it is written like this
````@child_text = @child.para "Okay, popped up from #{@**owner**}"

You can see also that the entries that are created in the child flow appear on the master canvas which is nuts.

@ccoupe  what do you think?

```Ruby
Shoes.app title: "The Owner" do
   
	@child = nil 	# Variable for the new window
	
	button "Pop up?" do
		if not @child.nil? then  # if window exists close it, new one will be open
			@child.close
		end
		@child = window do end
		@child.slot.flow( left: 20, top: 60, width: 100, height: 100) do
			border("rgb(105, 105, 105)", strokewidth: 5)
			para "Flow is on the child but border and para are on the owner?"
		end
		@child_text = @child.para "Okay, popped up from #{@child.owner}"
		@el = @child.edit_line do |e|
		      @child.slot.contents.para e.text+"\n"
		      @child_text.text = e.text
		end
		@el.finish = proc { |slf| @child.para "enterkey #{slf.text}\n" }
    end
 end
```

**Comment by dredknight** [comment]
@arjunmenon if you want to create app with multiple windows and download capabilities go ahead and download [this app](http://www.moddb.com/mods/heroes-v-new-creature-framework/downloads/ncf-utility-setup).  Install it somewhere and open main.rb. When you execute it you will see what is going on.

It allows you to have multiple windows on one frame where download tasks can continue work in the background.

App code can be see [here ](https://github.com/dredknight/Heroes-5-modding-scripts/blob/master/NCF_configuration_app/main.rb) too,

I am pretty sure there is an article in the wiki explaining multiple windows approach but I could not find it. Or may be I was about to write it? @ccoupe  do you have any idea did I do such thing?

Cheers!

**Comment by owner** [comment]
i'm @owner. wozzup?

**Comment by BackOrder** [comment]
Привет @owner, как дела? Добро пожаловать в Shoes)))

**Comment by dredknight** [comment]
Hello @owner  I am sorry for tagging you ! I have not even realized that :). Welcome to Shoes!

**Comment by ccoupe** [comment]
Closing. The App structure/paradigm is too ingrained in Shoes code to be changed in Shoes 3 or 4.
