### ISSUE TITLE
Support for transparency in GUI?

### ISSUE THREAD

**Issue by LWFlouisa** [shoes/shoes3#412]
Before I request, how do to do hashtags on here?

Anyway, is there a way to add transparency to GUI windows? The situation I'm thinking of specifically is developing for stuff like google glass, but not google glass.

I'm wanting to do games and apps for non augmented reality too of course, but I wanted to ask ahead of time before fruitlessly searching.

**Comment by ccoupe** [comment]
Hi @LWFlouisa  - there is very limited support for the Windows. From the manual:
```ruby
Shoes.app do
   @b = banner "Opacity\n"

   slider fraction: 1.0 do |n|
      app.opacity = n.fraction
      @b.text = "Opacity %.2f\n" % n.fraction
   end
end
```

**Comment by LWFlouisa** [comment]
Thanks! Figured it out.:D
