### ISSUE TITLE
Shoes 3.3.6 does not open after installation

### ISSUE THREAD

**Issue by dredknight** [shoes/shoes3#413]
Dear all,

A fan that installed the packaged manual app reported that it does not open. 
I asked him instead of the exe to try opening main.rb a window appeared and instantly closed.

He said he has ruby interpreter and ruby on rails installed on that host. I asked him to uninstall them , reboot and try again. The results were the same as before.

Then I asked him to install latest stable shoes (3.3.6) because I thought some global vars could have been compromised and by installing the shoes I hoped they would be overwritten. Unfortunately there was no change. Moreover it seems that Shoes behaves the same as the app. So the issue is ruby.

@ccoupe do you have any suggestion where to look for?

**Comment by ccoupe** [comment]
My concerns are several. Your packaged app (from exe-shoes) should not interfere with anything already installed be it ruby, rails or anything else.  

Was their Ruby and Rails working before? 
Which ruby was it? - who provided it? - which ruby version?
Check the ENV vars on that system - There could be leftovers from previous installs that are causing a problem  Installing Shoes DOES NOT remove global vars but it will add to ENV.  Un-insttalling Shoes may get rid of a few ENV vars but that probably won't fix anything now - still a could idea. Get their ruby/rails working again.

**Comment by dredknight** [comment]
Thank you @ccoupe I will check those stuff! I am pretty sure there is nothing to do with the packaged app because this is the first such complain after 1700 downloads. Also as I said above installing Shoes 3.3.6 and running its main menu does not work as well (just like the app) so something global should be the issue.

**Comment by dredknight** [comment]
We tried removing all ruby globals and deploying stuff again but nothing worked.
