### ISSUE TITLE
tooltip not working  under certain conditions.

### ISSUE THREAD

**Issue by dredknight** [shoes/shoes3#414]
Dear all,

I think I may have found a bug with "tooltip" option.
I use Shoes 3.3.6 r3173

When executing this code, all buttons are defined the same way and have the same tooltip. However in 
 practice button "1" tooltip does not work while button "2" tooltip works.

```Ruby
Shoes.app do
	flow left: 0.05, top: 0.1, width: 0.9, height: 0.9 do
		@one = flow left: 0.06, top: 0.2, width: 0.5, height: 0.8 do
			button "1", tooltip: "asdsdsadda", left: 50, top: 200;
		end
		@two = flow left: 0.05, top: 0.1, width: 0.9, height: 0.9 do
			button "2", tooltip: "asdsdsadda", left: 50, top: 220;
		end
		@three = flow left: 0.05, top: 0.1, width: 0.9, height: 0.9 do
			button "3", tooltip: "asdsdsadda", left: 100, top: 220;
		end
	end
end
```

Adding one more "1" and "2" does not work while "3" works.

```Ruby
Shoes.app do
	flow left: 0.05, top: 0.1, width: 0.9, height: 0.9 do
		@one = flow left: 0.06, top: 0.2, width: 0.5, height: 0.8 do
			button "1", tooltip: "asdsdsadda", left: 50, top: 200;
		end
		@two = flow left: 0.05, top: 0.1, width: 0.9, height: 0.9 do
			button "2", tooltip: "asdsdsadda", left: 50, top: 220;
		end
		@three = flow left: 0.05, top: 0.1, width: 0.9, height: 0.9 do
			button "3", tooltip: "asdsdsadda", left: 100, top: 220;
		end
	end
end
```

It seems there is a pattern where only the last one works. It does not matter if the slots are defined by decimals or flats the result is always the same.

```Ruby
Shoes.app do
	flow left: 100, top: 100, width: 600, height: 600 do
		@one = flow left: 50, top: 50, width: 400, height: 400 do
			button "1", tooltip: "asdsdsadda", left: 10, top: 200;
		end
		@two = flow left: 50, top: 50, width: 400, height: 400 do
			button "2", tooltip: "asdsdsadda", left: 80, top: 220;
		end
		@two = flow left: 50, top: 50, width: 400, height: 400 do
			button "3", tooltip: "asdsdsadda", left: 150, top: 220;
		end
	end
end
```

The only time when it works is when the inner slots does not have defined dimensions.
In the example bellow "1" is not working but "2" (no dimensions slot) and "3" (because it is in the last drawn slot which is on top of the others) are working.

```Ruby
Shoes.app do
	flow left: 100, top: 100, width: 600, height: 600 do
		@one = flow left: 50, top: 50, width: 400, height: 400 do
			button "1", tooltip: "asdsdsadda", left: 10, top: 200;
		end
		@two = flow left: 100, top: 100 do
			button "2", tooltip: "asdsdsadda", left: 80, top: 220;
		end
		@two = flow left: 50, top: 50, width: 400, height: 400 do
			button "3", tooltip: "asdsdsadda", left: 150, top: 220;
		end
	end
end
```

I believe this bug happens because slots overlap each other and tooltip appears only in the slot of the element but for some reason the upper slots (even though they are transparent) does not allow for the tooltip to appear.

@BackOrder I believe that you implemented that deep in the C code. Any idea what may have gone wrong?

**Comment by ccoupe** [comment]
Tooltips in gtk are properties of the native widget (i.e.button),  **not** the slot.  If buttons overlap then you may or may not get the one you want and you definitely have to wait the proper time for it to show.

**Comment by dredknight** [comment]
I see but this happens even if the buttons do not overlap. :/

**Comment by dredknight** [comment]
I did a test with this issue, it seems the GTK update was a good choice! Things are working perfect in any occasion. Check this code 1 and 2 both work and give their own tooltip. 

Closing the issue. Many thanks!

```Ruby
Shoes.app do
	flow left: 0.05, top: 0.1, width: 0.9, height: 0.9 do
		@one = flow left: 0.06, top: 0.15, width: 0.5, height: 0.8 do
			button "1", tooltip: "qqqqqqqqqq", left: 50, top: 200;
		end
		@two = flow left: 0.05, top: 0.1, width: 0.9, height: 0.9 do
			button "2", tooltip: "asdsdsadda", left: 50, top: 220;
		end
		@three = flow left: 0.05, top: 0.1, width: 0.9, height: 0.9 do
			button "3", tooltip: "asdsdsadda", left: 100, top: 220;
		end
	end
end
```
