### ISSUE TITLE
Shoes and Visual studio dependencies compatibility

### ISSUE THREAD

**Issue by dredknight** [shoes/shoes3#416]
Hey @ccoupe and @BackOrder ,

Just got an interesting feedback.
One of the people using shoes app cannot launch it. He gets a C++ error.
He has Visual studio installed

He managed to fix this by doing the following:
- run cmd as administrator
- "bcdedit.exe /set IncreaseUserVA 2800" and restart the pc everytime. 
Looks like shoes and Visual Studio aren't compatible

Not sure if this can be of any help but decided to posted it in case it can give you any tips.
Cheers

**Comment by ccoupe** [comment]
I wouldn't be surprised if an installed msvc ruby and a installed mingw ruby (RubyInstalller) interfered with each other but Shoes should be isolated from that. **Should be.**  The C++ error maybe misleading. The inability to run Shoes packaged apps via a new Shoes install on  Win 10 , .aka. the signing problem, is reported to come with a C++ error message. I've also seen C++ error messages on my machine which doesn't not have C++ (or VS) but that was for different error, long ago. 

The boot edit solution strikes me a very peculiar (odd) but I know very little about that stuff in Windows.

**Comment by ccoupe** [comment]
Without more feedback, I'm closing this issue.
