### ISSUE TITLE
Download link »Shoes 3.3.6 for just OSX 10.9« returns an 404 error.

### ISSUE THREAD

**Issue by bolandross** [shoes/shoes3#417]
On the page: http://shoesrb.com/downloads/

the link for [Shoes 3.3.6 for just OSX 10.9](https://shoes.mvmanila.com/public/shoes/shoes-3.3.6-osx-10.9.tgz) returns an error.

**Comment by ccoupe** [comment]
Thanks for pointing out the error. It's deleted now.
