### ISSUE TITLE
Question about Shoes build dependencies

### ISSUE THREAD

**Issue by tuttza** [shoes/shoes3#420]
Hi Guys,

I am trying to build Shoes on the new Fedora 29 and I am also working on updating the Fedora build instructions in the wiki (https://github.com/shoes/shoes3/wiki/Building-Shoes-on-Linux).

My question is: Do I need to install the 32-bit development packages? I ask because the 64-bit devel packages are installed by default. For example:
```
cairo-devel.i686 : Development files for cairo
cairo-devel.x86_64 : Development files for cairo
```
The x86_64 is the one that gets installed by default when running `sudo dnf install cario-devel` 

I am asking all this right now because when I run the `rake` command in the `minlin/env.rb` its spits out "unknown architecture" when I look at the code its expecting some i386 package to exist, so am I assuming correctly that all the libraries that are needed have to be the 32 bit packages?

I need to know for my instructions and! also so I can actually "make" some Shoes! :smile:

**Comment by ccoupe** [comment]
Hi, nice to see someone working with the source!  There shouldn't be any 32 bit requirement for the minlin target unless some other sub-dependency drags it in - a real possibility, The wiki article is behind the times re: the master branch rake files and certainly behind the times for fedora. 
Make sure to start with `rake setup:minlin` Then you can do 'rake' and 'rake clean' as needed.  Make sure your ruby is 2.3.7 OR LESS. If your using rbenv then know that there may be rvm dependencies in some of the rake files.  I wouldn't be surprised if 'libgif' or 'libungif' is not found correctly.

**Comment by ccoupe** [comment]
@tuttza , I've updated that wiki page to be more accurate including the need to install some gems.

**Comment by tuttza** [comment]
@ccoupe Thanks! I will give it a try.

**Comment by tuttza** [comment]
Hi @ccoupe 

I am getting a little bit further. I finally get more that just `unknown architecture` when running `rake setup:minlin`

When I run the `rake` command I get this output:
```
[ztuttle@box01 .shoes-dev]$ rake
rake ruby: /home/ztuttle/.rvm/rubies/ruby-2.3.7
mkdir -p minlin
Package gtk+-3.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtk+-3.0.pc'
to the PKG_CONFIG_PATH environment variable
Package 'gtk+-3.0', required by 'virtual:world', not found
Package gtk+-3.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtk+-3.0.pc'
to the PKG_CONFIG_PATH environment variable
Package 'gtk+-3.0', required by 'virtual:world', not found
Package gtk+-3.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtk+-3.0.pc'
to the PKG_CONFIG_PATH environment variable
Package 'gtk+-3.0', required by 'virtual:world', not found
unknown architecture
```

but I am not sure why, I (think) I installed the gtk-3 libraries:

```
[ztuttle@box01 .shoes-dev]$ sudo dnf install gtk3-devel
Last metadata expiration check: 0:09:15 ago on Thu 06 Dec 2018 09:52:31 PM PST.
Package gtk3-devel-3.24.1-1.fc29.i686 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
```
Is it a different package than what I have installed?

**Comment by tuttza** [comment]
Actually I just re-installed it and now I am back to where I started:
```
[ztuttle@box01 .shoes-dev]$ rake
rake ruby: /home/ztuttle/.rvm/rubies/ruby-2.3.7
mkdir -p minlin
unknown architecture
```

**Comment by tuttza** [comment]
From the `shoes/make/linux/minlin/env.rb`
```ruby
MISC_CFLAGS = ' '
if File.exist? '/usr/lib/arm-linux-gnueabihf'
  ularch = 'arm-linux-gnueabihf'
elsif File.exist? '/usr/lib/x86_64-linux-gnu'
  ularch = 'x86_64-linux-gnu'
elsif File.exist? '/usr/lib/i386-linux-gnu'
  ularch = 'i386-linux-gnu'
else
  abort 'unknown architecture'
end
```

I feel like this will always return `unknown architecture` 

when I search the `/usr/lib` directory on my system I get this:
```
[ztuttle@box01 .shoes-dev]$ ls /usr/lib | grep "linux"
ld-linux.so.2
libselinux.so.1
libxcb-xselinux.so.0
libxcb-xselinux.so.0.0.0
```

is there something I need to install to get those in there?

**Comment by ccoupe** [comment]
@tuttza, we are dependent on pkg-config being correctly set up. if you have locate: `$locate gtk+-3.0.pc`
or use `find / -name gtk+-3.0.pc -print`. There's also a command line arg to pkg-config to display its settings. Assuming you have it, if not it needs to be installed - in debian, it's part of build-essentials package. 

Shoes has to figure out the location of librsvg-2.so (because pkg-config usually has it wrong) and its very repo dependent on where it is. Search for that and then modify that section of env.rb so ularch points to where librsvg-2.so lives. (you may need to install the devel package for it). 

On more thing, you're not at the point where everything is setup correctly for rake (env.rb has to work to get to that point). So, you need to do a `rake clobber`, `rake setup`, `rake` for each attempt. Once it starts to compile then you can just use 'rake'.

**Comment by tuttza** [comment]
@ccoupe Thanks for bearing with me! 

That `find / -name gtk+-3.0.pc -print` command did in fact find those! Just in a new location and I found the `libsvg-2.so`:
```
/usr/lib/pkgconfig/gtk+-3.0.pc
/usr/lib64/pkgconfig/gtk+-3.0.pc
/usr/lib64/librsvg-2.so
```
That's good to know. I'm assuming we will need to update that in the setup code to find these libraries with the new locations.

To give you an idea of what I am doing (all this running rvm with ruby 2.3.7 and all the development dependencies installed, including libsvg-2 which wasn't installed so thank you :bowing_man:  )
1. Clone the Shoes project
2.  `cd` into it
3. `bundle install`
4. I run `rake setup:minlin` this is about as far as I have gotten.

The weird thing is, after running  `rake setup:minlin` I cannot run any other rake commands unless I delete the repo and re-clone it. Essentially once I run the `rake setup:minlin` task,  every time I attempt to run `rake clobber` or  even a simple `rake -T` it acts like it's running the `rake setup` task and keeps printing:
```
[ztuttle@box01 .shoes-dev]$ rake -T
rake ruby: /home/ztuttle/.rvm/rubies/ruby-2.3.7
mkdir -p minlin
unknown architecture
```
Making progress :+1:  have a good weekend.

**Comment by ccoupe** [comment]
Don't do the bundle install - it should be harmless but shoes3  doesn't use bundler to build (or run) 

minlin/env.rb is loaded for every rake command so if it dies (the abort cmd) nothing runs. you can 'rm build_target' which is where rake setup stores the chosen target.  I just committed a fix that should get you going and still works for debian based systems.

**Comment by tuttza** [comment]
@ccoupe Oh yeah were in business now!


After pulling your new changes down I was able to start the build.

```
new_link: minlin from minlin/shoes
gcc -o minlin/shoes  minlin/tmp/main.o minlin/shoes.lib -L. -rdynamic -Wl,-export-dynamic -L/home/ztuttle/.rvm/rubies/ruby-2.3.7/lib -Wl,-rpath,$/../lib -Wl,-rpath,$/../lib -lruby -lpthread -ldl -lcrypt -lm -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0  -lcairo -lpango-1.0 -lgobject-2.0 -lglib-2.0  -lgif -ljpeg /usr/lib64/librsvg-2.so -lyaml -lfontconfig
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-redhat-linux/8/../../../libgif.so when searching for -lgif
/usr/bin/ld: skipping incompatible //lib/libgif.so when searching for -lgif
/usr/bin/ld: skipping incompatible //usr/lib/libgif.so when searching for -lgif
/usr/bin/ld: cannot find -lgif
collect2: error: ld returned 1 exit status
rake aborted!
```

Should I try and remove my the 64-bit gcc and install the 32 bit version? I assume thats what they mean by "incompatible"

**Comment by ccoupe** [comment]
I installed fedora 29 in a VM and updated the wiki article (the fedora changes replace the ancient ones and they were really old. I can compile and link Shoes. It doesn't run - not finding a libruby.so.2.3 - I suspect I can fix that in a few more minutes.

**Comment by ccoupe** [comment]
I've got it building and running with the latest commit. There appears to be gtk3 or theme issues. Pretty serious for some people. If you run scripts from the command line they might be ok
```minlin/shoes samples/good/cardflip.rb```

**Comment by tuttza** [comment]
@ccoupe going to try again, Thanks for the help

**Comment by tuttza** [comment]
@ccoupe I pulled down the new changes and did `rake clobber` then ran `rake setup:minlin` and `rake`
this what I keep running into now:

```
[ztuttle@box01 .shoes-dev]$ rake
rake ruby: /home/ztuttle/.rvm/rubies/ruby-2.5.3
mkdir -p minlin
rlib: -Wl,--compress-debug-sections=zlib -Wl,-rpath,$/../lib -Wl,-rpath,$/../lib -lruby -lpthread -ldl -lcrypt -lm
fixed: -L/home/ztuttle/.rvm/rubies/ruby-2.5.3/lib -Wl,--compress-debug-sections=zlib -Wl,-rpath,/home/ztuttle/.rvm/rubies/ruby-2.5.3/lib -Wl,-rpath,/home/ztuttle/.rvm/rubies/ruby-2.5.3/lib -lruby -lpthread -ldl -lcrypt -lm
/home/ztuttle/.shoes-dev/make/linux/minlin/env.rb:66: warning: already initialized constant DEBIAN
/home/ztuttle/.shoes-dev/make/linux/minlin/env.rb:60: warning: previous definition of DEBIAN was here
touch minlin/tmp/zzbase.done
gcc -o minlin/tmp/version.o -I. -c -g -O0 -DRUBY_HTTP -DRUBY_1_9 -DSZBUG -DSHOES_GTK -fPIC -shared -Wno-unused-but-set-variable -I/usr/include/ -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/uuid -I/usr/include/harfbuzz -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/libdrm -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -pthread  -I/home/ztuttle/.rvm/rubies/ruby-2.5.3/include/ruby-2.5.0/x86_64-linux -I/home/ztuttle/.rvm/rubies/ruby-2.5.3/include/ruby-2.5.0 -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/uuid -I/usr/include/harfbuzz -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/libdrm -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -pthread -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/uuid -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/fribidi  -I/usr/include/librsvg-2.0/librsvg  shoes/version.c
new_so: minlin from /home/ztuttle/.shoes-dev/minlin/libshoes.so
ar -rc minlin/shoes.lib minlin/tmp/app.o minlin/tmp/canvas.o minlin/tmp/image.o minlin/tmp/internal.o minlin/tmp/main.o minlin/tmp/ruby.o minlin/tmp/version.o minlin/tmp/world.o minlin/tmp/http/rbload.o minlin/tmp/plot/chart_series.o minlin/tmp/plot/plot.o minlin/tmp/plot/plot_column.o minlin/tmp/plot/plot_line.o minlin/tmp/plot/plot_pie.o minlin/tmp/plot/plot_radar.o minlin/tmp/plot/plot_scatter.o minlin/tmp/plot/plot_util.o minlin/tmp/console/colortab.o minlin/tmp/console/gtk-terminal.o minlin/tmp/console/tesi.o minlin/tmp/types/button.o minlin/tmp/types/check.o minlin/tmp/types/color.o minlin/tmp/types/download.o minlin/tmp/types/edit_box.o minlin/tmp/types/edit_line.o minlin/tmp/types/effect.o minlin/tmp/types/event.o minlin/tmp/types/image.o minlin/tmp/types/list_box.o minlin/tmp/types/menu.o minlin/tmp/types/menubar.o minlin/tmp/types/menuitem.o minlin/tmp/types/native.o minlin/tmp/types/pattern.o minlin/tmp/types/plot.o minlin/tmp/types/progress.o minlin/tmp/types/radio.o minlin/tmp/types/settings.o minlin/tmp/types/shape.o minlin/tmp/types/slider.o minlin/tmp/types/spinner.o minlin/tmp/types/svg.o minlin/tmp/types/switch.o minlin/tmp/types/systray.o minlin/tmp/types/text.o minlin/tmp/types/text_link.o minlin/tmp/types/text_view.o minlin/tmp/types/textblock.o minlin/tmp/types/timerbase.o minlin/tmp/types/video.o minlin/tmp/native/gtk.o minlin/tmp/native/gtkbuttonalt.o minlin/tmp/native/gtkcheck.o minlin/tmp/native/gtkcomboboxtextalt.o minlin/tmp/native/gtkcss.o minlin/tmp/native/gtkeditbox.o minlin/tmp/native/gtkeditline.o minlin/tmp/native/gtkentryalt.o minlin/tmp/native/gtkfixedalt.o minlin/tmp/native/gtkmenus.o minlin/tmp/native/gtkprogressbaralt.o minlin/tmp/native/gtkradio.o minlin/tmp/native/gtkscrolledwindowalt.o minlin/tmp/native/gtkslider.o minlin/tmp/native/gtkspinner.o minlin/tmp/native/gtkswitch.o minlin/tmp/native/gtksystray.o minlin/tmp/native/gtktextview.o minlin/tmp/native/gtktimerbase.o minlin/tmp/native/gtkvideo.o
ranlib minlin/shoes.lib
new_link: minlin from minlin/shoes
gcc -o minlin/shoes  minlin/tmp/main.o minlin/shoes.lib -L. -rdynamic -Wl,-export-dynamic -L/home/ztuttle/.rvm/rubies/ruby-2.5.3/lib -Wl,--compress-debug-sections=zlib -Wl,-rpath,/home/ztuttle/.rvm/rubies/ruby-2.5.3/lib -Wl,-rpath,/home/ztuttle/.rvm/rubies/ruby-2.5.3/lib -lruby -lpthread -ldl -lcrypt -lm -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0  -lcairo -lpango-1.0 -lgobject-2.0 -lglib-2.0  -lgif -ljpeg /usr/lib64/librsvg-2.so -lyaml -lfontconfig
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-redhat-linux/8/../../../libgif.so when searching for -lgif
/usr/bin/ld: skipping incompatible //lib/libgif.so when searching for -lgif
/usr/bin/ld: skipping incompatible //usr/lib/libgif.so when searching for -lgif
/usr/bin/ld: cannot find -lgif
collect2: error: ld returned 1 exit status
rake aborted!
Command failed with status (1): [gcc -o minlin/shoes  minlin/tmp/main.o min...]
/home/ztuttle/.shoes-dev/make/linux/minlin/tasks.rb:79:in `new_link'
/home/ztuttle/.shoes-dev/Rakefile:445:in `block in <top (required)>'
/home/ztuttle/.rvm/gems/ruby-2.5.3/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/home/ztuttle/.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `eval'
/home/ztuttle/.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => default => build => linux:build => new_build
(See full trace by running task with --trace)
```

I verified that I have all the C library dependencies installed,

```
[ztuttle@box01 .shoes-dev]$ sudo dnf install -y giflib-devel cairo-devel pixman-devel pango-devel libjpeg-turbo-devel gtk2-devel libcurl-devel librsvg2-devel ruby-devel
Last metadata expiration check: 1:43:31 ago on Fri 07 Dec 2018 08:19:05 PM PST.
Package giflib-devel-5.1.4-2.fc29.i686 is already installed.
Package cairo-devel-1.16.0-1.fc29.x86_64 is already installed.
Package pixman-devel-0.34.0-10.fc29.i686 is already installed.
Package pixman-devel-0.34.0-10.fc29.x86_64 is already installed.
Package pango-devel-1.42.4-1.fc29.x86_64 is already installed.
Package libjpeg-turbo-devel-2.0.0-1.fc29.x86_64 is already installed.
Package libjpeg-turbo-devel-2.0.0-1.fc29.i686 is already installed.
Package gtk2-devel-2.24.32-3.fc29.x86_64 is already installed.
Package libcurl-devel-7.61.1-5.fc29.x86_64 is already installed.
Package libcurl-devel-7.61.1-5.fc29.i686 is already installed.
Package librsvg2-devel-2.44.9-1.fc29.x86_64 is already installed.
Package ruby-devel-2.5.3-99.fc29.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
```

Am I missing something?

**Comment by tuttza** [comment]
@ccoupe Appropriate your help in getting this going for me. 

I've read your blog about what is going on but I'm not sure what your trying to do or what needs worked on, maybe menus, layout?. Is there any particular area you want to have worked on?

**Comment by ccoupe** [comment]
@tuttza 
> Am I missing something?

Those incompatible libs are probably from  the really really old list of installs. Remember how I warned about libgif? New fedora's seemed to have fixed that mess. There are serious GUI issues easily seen with just a `minlin/shoes`. Offset for the mouse is wrong. Windows can't be moved.  I'm not sure what Fedora did to the gtk theme to cause that or how I can detect and workaround it. I saw this behavior on another linux where they did 'non-standard' things. I'm not a fan of the Gnome Shell so I never use it.

> Is there any particular area you want to have worked on?

If you want to work in C with Gtk3 there's a lot of things to be done. As you'll see, the github master branch is the 3.3.7 beta. It's got a Gtk3 resize bug when menu's are used. If you want to work in Ruby there's work to do on the 'direwolf' git branch (3.3.8 beta) dealing with the cassowary layout. Lot of testing to do of course.  I really need to fix the gtk3 bugs on fedora. The manual doen't work like it does on ubuntu. `minlin/shoes -m`

**Comment by ccoupe** [comment]
I installed the shoes 3.3.6 binary in my fedora 29 VM - same gui issues. That means it's not my 3.3.7 menu stuff. Gtk is 3.24.1. That's recent. I vaguely remember some warning I read somewhere (gtk manual?) that mouse reporting changed it's baseline.  That could also be the problem @dredknight logged about Win 10 and newer Gtk3.

**Comment by tuttza** [comment]
@ccoupe I am looking to work on the lower level stuff (C, gtk, C ruby). I will start to dig into these mouse/window issues. Where do recommend I start within the project, maybe the gtk.h/gtk.c?

**Comment by ccoupe** [comment]
@tuttza. OK! We need more low level help.  That part of Shoes is  confusing for new comers. You may have noticed a lot of debugging printf's on the launch terminal. There's a -D option set in minlin/env.rb for that but more importantly there is the code. They are there  for the resize bug, when menus are enabled, windows can can be expanded but they can't be shrunk.  Since the manual isn't working on Fedora it going to be hard to read the details for menu support.  There are some small scripts in Tests/menus that you can run to get familiar. Also [the wiki article](https://github.com/shoes/shoes3/wiki/Menus) and [this one.](https://github.com/shoes/shoes3/wiki/Shoes-3.3.7)

**Comment by ccoupe** [comment]
@tuttza , yes shoes/native/gtk.c is where the window sizing code is but you'll need to learn where all the other code lives since it's not all that modular.

**Comment by tuttza** [comment]
@ccoupe Thanks, I will start messing around the source.

In the mean time I created a Gitter chat room for this shoes project so that we(and others) can talk in the chat room to ask and answer questions: https://gitter.im/ruby-shoes/Lobby#

I sent you an invite.

**Comment by ccoupe** [comment]
@tuttza - the latest commit should get you working if you have windows with menus. To enable menus for the splash screen, create a 'startup.yaml' that looks like this:
```txt
App_Name: Foobar
#Icon_Path: static/shoes-icon-blue.png
#Theme: XP 
Use_Menus: true
```

**Comment by tuttza** [comment]
@ccoupe thanks, I will try it out. I saw your comment in gitter about the mouse position issue. I will take a look at your commit.

**Comment by ccoupe** [comment]
Closing 3.3.7 issues.
