### ISSUE TITLE
Windows 10 and Shoes 3.3.7

### ISSUE THREAD

**Issue by ccoupe** [shoes/shoes3#428]
Only happens when menu==false and Gtk3.33.7 and Win10 -- when that happens we need to use the menu offsets

**Comment by ccoupe** [comment]
@dredknight , can you try the new beta of 3.3.7?  It works on my Win 10 and Win 7, with or with out menus enabled.

**Comment by dredknight** [comment]
@ccoupe with and without menus (true and false) it works properly every time! How did you fix it? Some global mouse offsets?

**Comment by dredknight** [comment]
@ccoupe I have to do more thorough tests at some point :). My speed opinion is purely subjective.
