### ISSUE TITLE
Radio points element visual misbehave

### ISSUE THREAD

**Issue by dredknight** [shoes/shoes3#433]
Shoes build: 3.3.7 - 3302
All radio points in the cluster are shown as pressed.
Functional wise it is working properly when clicked. 
Visually they are always all pressed.

![image](https://user-images.githubusercontent.com/12410314/54959939-72546180-4f63-11e9-8018-6373d532ed0b.png)

**Comment by ccoupe** [comment]
Shoes 3.3.7 chnage radio and tightened the rules. There is _no_ default for a Radio cluster (group). On Gtk it is  often is the first radio but that can not be assumed, particularly for OSX.  The rules for radios that are not in a group is that they have a 'hidden' group of one radio (so it is often on) and can't be unset by the user. If you think about it deeply, that makes sense - In a group, there is always one that has to be set. You would want checkbox for that situation.

I can't tell how your radio's are grouped. You might want to make sure the group name is a symbol - **:**symbol)=.

**Comment by dredknight** [comment]
@ccoupe those radios were made quite some versions behind (3.3.2 ~3.3.3) so I assume the code should be reiterated to follow the new rules. I will check and let you know.

**Comment by ccoupe** [comment]
The rule should be "a group name" is required for radio buttons". I thought about enforcing that but it's not backwards compatible. Then again the old system was broken.  It just _happened_ to work for some people, some of the time.

**Comment by dredknight** [comment]
I tried the following error but it breaks the stack. did I do something wrong?

```Ruby
Shoes.app do

radio(group: "one", left: 10, top: 10)
radio(group: "one", left: 10, top: 30)
radio(group: "one", left: 10, top: 50)
radio(group: "one", left: 10, top: 70)

end

```

**Comment by dredknight** [comment]
My bad the syntax is wrong. This one works:

`Shoes.app do

radio(:one, left: 10, top: 10)
radio(:one, left: 10, top: 30)
radio(:one, left: 10, top: 50)
radio(:one, left: 10, top: 70)

end`
