### ISSUE TITLE
Shoes cannot operate properly if not run as an admin

### ISSUE THREAD

**Issue by dredknight** [shoes/shoes3#435]
I tried to install a remote gem but got the following error

![image](https://user-images.githubusercontent.com/12410314/55195843-69a79980-51b6-11e9-9ad3-2a9f6917d8ef.png)

The issue is that Shoes does not have enough rights to create folder so it doesnt do it and get this error.

If I "Run as Administrator" Shoes things are fine.
Not sure if this is an issue but decided to register it for the sake of housekeeping.

P.S.

When I list local gems and go to Rubyzip and click "Load test" I get this message
![image](https://user-images.githubusercontent.com/12410314/55196187-4af5d280-51b7-11e9-9429-11816b4ba7c2.png)

And when I click "OK" i get this one.

![image](https://user-images.githubusercontent.com/12410314/55196216-56e19480-51b7-11e9-873b-7e65650c4600.png)

I believe for some reason rubyzip is not working properly anymore.

**Comment by ccoupe** [comment]
@dredknight - that's an error!  Shoes should be installing gems in your user area % APPDAT% and shouldn't be playing in your installed shoes area.  It is  possible the gem is asking for something else though. The manifest/spec  would have the clue.  Many gems fail the Cobbler load test but are perfectly good. It's safe to ignore that - assuming you can require the gem in your code. That's the better test.

**Comment by dredknight** [comment]
Unfortunately I cannot require the gem in the code :(

**Comment by ccoupe** [comment]
You can try to delete it from cobbler. There is a zip writer built in to Shoes - it's how we create osx distributions although there are some peculiarities for Windows, presumably that's why the [rubyzip project ](https://github.com/rubyzip/rubyzip/issues)exists.

**Comment by ccoupe** [comment]
On my Windows 7 the rubyzip gem installed fine. The spec file is in at C:\Users\Cecil\AppData\Local\VirtualStore\Program Files (x86)\Shoes\lib\ruby\gems\2.3.0\specifications .  It's AppData\Local but after that the name has changed to include that VirtualStore stuff. I don't remember that. BTW, the load test works on that one.  I know you are on Win 10. Is Shoes marked for Win 7 compatibility?

**Comment by dredknight** [comment]
Not sure what it was but uninstall, restart and install shoes fixed the issue. Thank you!
