### ISSUE TITLE
Shoes Console not copying stack trace with error message

### ISSUE THREAD

**Issue by apjanke** [shoes/shoes3#442]
I'm running Shoes 3.3.7 r3301 on macOS 10.14.5.

I'm trying to get my app running, and it's encountering an error on startup. The console displays an error message with a stack trace:

<img width="911" alt="Screen Shot 2019-05-27 at 8 30 28 AM" src="https://user-images.githubusercontent.com/2618447/58419849-b1815a80-8059-11e9-981f-be1b1cb9cdbd.png">

But when I hit the Copy button, it only includes the error messages, omitting the stack trace. Here's what I get when I Copy and then paste:

```
Warn in <unknown> line 0 | 2019-05-27 08:27:42 -0400
Ignoring jaro_winkler-1.3.7 because its extensions are not built.  Try: gem pristine jaro_winkler --version 1.3.7

Error in <unknown> line 0 | 2019-05-27 08:27:58 -0400
uninitialized constant Psych::Syck::PrivateType
Did you mean?  Psych::PrivateType
```

Is this intentional? It would be useful to have the stack trace included in the error message for pasting into bug reports.

**Comment by ccoupe** [comment]
I _think_ this a bug from the newer Ruby in shoes 3.3.8. The stack dump did change in 2.4. I saw the problem yesterday working on a Windows problem and thought it strange.

**Comment by ccoupe** [comment]
Please try the beta for Shoes 3.3.8 for it's better handling of gems. The version I used in my responce has been [uploaded to here](https://walkabout.mvmanila.com/public/shoes/shoes-3.3.8-osx-10.10.tgz)

**Comment by apjanke** [comment]
I tried the new Shoes 3.3.8 r3371 beta, and it appears to be copying the full stack trace correctly now.

Closing this out as fixed; will re-open if the issue reoccurs.
