### ISSUE TITLE
Image Clearing in Shoes 3

### ISSUE THREAD

**Issue by LWFlouisa** [shoes/shoes3#455]
Operating System: Linux Mint 19.1

Issue: Image not clearing, work around solutions have mixed results.

Issue In Depth: 
A kind person mention maybe filing the issue in Shoes 3. My main issue seems to be an image caching problem. I generate the QR Code using RQRCode in an external program, and have shoes simply display the image generated from the external script.

I did it that way, as it seems like certain ruby gems I've been using don't work quite the same in Shoes as it does in the terminal: specifically Gabbler.

I am able to write over the image, and have it display the new image when reloading the GUI. But that means exiting the application:

```ruby
Shoes.app do
  
  def clear_screen
    clear
  end
  
  def generate_poem
    system("ruby QRPoetry.rb")
  end
  
  def display_image
    image "poem.png"
  end
  
  def display_button
    button("Generate Poem") {
      c = clear_screen; i = image_clear; g = generate_poem; d = display_button; d = display_image
    }
    
    button("Exit") {
      exit
    }
  end
  
  flow do
    button("Generate Poem") {
      c = clear_screen; g = generate_poem; d = display_button; d = display_image
    }
    
    button("Exit") {
      exit
    }
  end
  
end
```

This was kind of a work around to the fact I was using app.clear instead of image.clear, which wasn't clearing the image.

I don't think the issue is with the QRPoetry in terminal form.

**Comment by ccoupe** [comment]
Hi @LWFlouisa . Thanks for the sample code. That helps. According to the manual you can control the cache by image call:
```ruby
 Shoes.app do
   image "http://shoesrb.com/img/shoes-icon.png", cache: false
 end
```
Or disable it for the whole app (unless overriden) with an
`app.cache = false`  

You do need one of them because as written, it's using the cached image. You'll need a recent Shoes 3, I'm not certain when I added the cache off code to Shoes but it was for reason you found. 

Clearing is a little more complex (easier in someways). 
```ruby
Shoes.app do
  stack do
    flow do
      button "Generate Poem" do
        system("ruby QRPoetry.rb")
        @imgflow.clear { image "poem.png", cache: false }
      end
      button "Exit" do
        exit
      end
    end
    @imgflow = stack do
      para "An Image will replace this text"
    end
  end
end
```
clear accepts a block so it's really doing a 'replace' contents.

**Comment by LWFlouisa** [comment]
Thanks so much! Will try this will the Compound Word And Definition Generation network thing now then.
