### ISSUE TITLE
Window resize

### ISSUE THREAD

**Issue by DrSloth** [shoes/shoes3#456]
Is there anyway to resize Shoes apps manually? Normal apps can be resized by dragging at the edges, but i found no way to do it with shoes. Fullscreen works but the clickable area of links aren't at the same spot as the links. 
I am using a Windows 10 PC.

Thanks in advance.

**Comment by ccoupe** [comment]
You can enable window resizing with an option passed to Shoes.app like:
```rubt
Shoes.app width: 350, height: 400, resizeable: true do

> Fullscreen works but the clickable area of links aren't at the same spot as the links. I am using a Windows 10 PC.

Which version of Shoes are you using? This bug keeps recurring and getting fixed only to show up again.

**Comment by DrSloth** [comment]
I am using shoes 3.3.7. I already tried that solution but it didn't work. The app window is behaving kind of weird in some ways, first this resizing issue and i also can't move the window. Everything else is working fine

**Comment by ccoupe** [comment]
You can try this test script from issue #372
```ruby
Shoes.app(width: 250, height: 100, resizable: false) do
    @p = para
    flow do
        button("enable") do
            app.resizable = true
        end
        button("disable") do
            app.resizable = false
        end
    end
    animate do
        @p.replace "resizable #{app.resizable}"
    end
end
```
my copy of 3.3.7 (I have lots of copies) is a little buggy with my Win 10, too. The [3.3.8 beta](https://walkabout.mvmanila.com/public/shoes/shoes-3.3.8-gtk3-32.exe) works better, for me.

**Comment by DrSloth** [comment]
Thank you very much the 3.3.8 is working very well on my machine.
