### ISSUE TITLE
icon

### ISSUE THREAD

**Issue by k13nismo** [shoes/shoes3#465]
I'm trying to use alert, but the image is broken.

Using alert at sample/good/reminder.rb
![alert](https://user-images.githubusercontent.com/25317392/92063835-1720d280-edd7-11ea-903b-3e1218e6c7f8.png)

And "Open file ..." as well.
![open](https://user-images.githubusercontent.com/25317392/92066552-230f9300-eddd-11ea-958b-499e102c827e.png)

any solutions?

**Comment by ccoupe** [comment]
Is this Windows ? Which version of Shoes?  Depending on that there may be a theme related bug. It's not likely to be fixed because I'm not writing code anymore.

**Comment by k13nismo** [comment]
Running on Ubuntu 20.04LTS.
There is no problem when 18.04LTS .
So, I expected some configure or libraries missing on my new environment.

**Comment by ccoupe** [comment]
For certain, Ubuntu 20.04 has a much newer gtk3 lib than shoes 3.3.6 is expecting.  Shoes 3.3.7 may help you - it's been out for a year or more. The 3.3.8 beta also has improvement with gtk3 but contains some regressions (which may not affect you)  - one reason it may never get out of beta. Gtk3 has been a moving target up to Gtk 3.24.nn with breaking changes and Shoes has a hard time maintaining compatibility with (say ) 3.10 and 3.24 using one Shoes app.  

> There is no problem when 18.04LTS . So, I expected some configure or libraries missing on my new environment.

Missing libraries will cause Shoes not to load at all. Wrong versions of libraries do cause problems. The choice of X11 or wayland affects Shoes (3.3.8 is better for wayland). Then there is what ubuntu and gnome have done with menus and themes.  If you start shoes from the commandline `$ ~/.shoes/walkabout/shoes path/to/file.rb` you may get some error complaints on the terminal that would be helpful. There are lot of knobs that can be turned with Gtk3/themes/Shoes.

**Comment by k13nismo** [comment]
For 3.3.7 and 3.3.8, I tried it in some hours ago, and didn't solve.
Another issue for 3.3.7/3.3.8, was that the size of the buttons had changed in my app... 

Thanks for your advice.
I will try various things.

**Comment by ccoupe** [comment]
Here is Shoes 3.3.6 on Mint 19.1 (
![image](https://user-images.githubusercontent.com/222691/92291198-b11a7500-eed4-11ea-9125-1cf040b87a0b.png)

It looks different on Raspbian - Buster
![image](https://user-images.githubusercontent.com/222691/92291672-f8a20080-eed6-11ea-8015-b8c6707e35c6.png)

I did have Ubuntu 20.04 on a Jetson Nano but I installed XFCE on it and it looks like the

**Comment by k13nismo** [comment]
xfwm4 change default theme on update.
I was downgrade 4.14 to 4.12, but display did not change.

![スクリーンショット 2020-09-09 10-52-04](https://user-images.githubusercontent.com/25317392/92545181-8d677e00-f28a-11ea-9091-d7692ab2f79b.png)

> If you start shoes from the commandline $ ~/.shoes/walkabout/shoes path/to/file.rb you may get some error complaints on the terminal that would be helpful. 

There no message. Shoes console(alt+/) as well.

**Comment by ccoupe** [comment]
If I had to guess, the icon that is being selected is too large or being resized larger than the space. A bug in Gtk3 and/or the theme and/or icons file or  Shoes is using an older Gtk Api. I can't replicate it so that's going to be hard to fix.  The code in question is https://github.com/shoes/shoes3/blob/b856f28795112ecb64bc8f891ac166675f059beb/shoes/native/gtk.c#L1738

There is a second bug --`OK(0)` should be just `OK`. That maybe another clue to what is going wrong.

**Comment by k13nismo** [comment]
Solve problems are hard to me, I give up.
As far as don't see the icon, my app is fine. 
I'm going to workaround this issue by displaying a messages in the "window" without using "alert".

Thank you for investigating.

**Comment by k13nismo** [comment]
Maybe cause was the icon theme.
Same issue was not confirm on Xubuntu 20.10 .
