### ISSUE TITLE
install old version of a gem?

### ISSUE THREAD

**Issue by dredknight** [shoes/shoes3#466]
Hey Cecil,

Is there any way to load an old version of rubyzip?
For example:

gem install rubyzip -v 1.3.0

When i type this in the Shoes cmd (alt + =) it does not work.
 I tried to install "gems" via the cobler but still the same.

**Comment by ccoupe** [comment]
.There are ways. Firgure out the OS  path of Shoes Gems -- `cshoes --gem path` Make sure the rubyzip is where gem ven is. The try 'cshoes --gem uninstall`  It could be done working with individual files but that is error prone, tedious and you'll never trust what you did.

**Comment by dredknight** [comment]
It worked !!
`C:\Program Files (x86)\Shoes\cshoes --gem install 'C:\Program Files (x86)\Shoes\rubyzip-1.3.0.gem'`
Thank you Cecil. I do added this piece of info to the Wiki:
- https://github.com/shoes/shoes3/wiki/Gems
